// packages/app/src/renderer/components/layout/topbar/TopBarUpdateNotice.tsx
import { Download, LoaderCircle, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import type { AppUpdateSnapshot } from "@codenexus/shared/ipc/contracts";
import { codexDesktop } from "../../../api/codexDesktopClient";

type TopBarUpdateNoticeProps = {
  className?: string;
};

const DEFAULT_STATE: AppUpdateSnapshot = {
  status: "idle",
  currentVersion: "0.0.0",
  latestVersion: null,
  releaseName: null,
  releaseNotes: null,
  updateAvailable: false,
  downloaded: false,
  progress: null,
  errorMessage: null,
  checkedAt: null,
  isPackaged: false,
};

function clampProgressPercent(value: unknown) {
  const percent = Number(value ?? 0);
  if (!Number.isFinite(percent)) return 0;
  return Math.max(0, Math.min(100, Math.round(percent)));
}

export default function TopBarUpdateNotice({ className }: TopBarUpdateNoticeProps) {
  const { t } = useTranslation();
  const [state, setState] = useState<AppUpdateSnapshot>(DEFAULT_STATE);
  const [actionRunning, setActionRunning] = useState(false);
  const visible = state.status === "available" || state.status === "downloading" || state.status === "downloaded";
  const progressPercent = clampProgressPercent(state.progress?.percent);

  useEffect(() => {
    let off: (() => void) | null = null;
    let mounted = true;
    void (async () => {
      off = codexDesktop.app.onUpdateState((next) => {
        if (mounted) setState(next);
      });
      const snapshot = await codexDesktop.app.getUpdateState();
      if (mounted) setState(snapshot);
    })();
    return () => {
      mounted = false;
      off?.();
    };
  }, []);

  const label = useMemo(() => {
    if (state.status === "downloading") return t("topbarUpdate.downloading", { percent: progressPercent });
    if (state.status === "downloaded") return t("topbarUpdate.install");
    return t("topbarUpdate.available");
  }, [progressPercent, state.status, t]);

  const ariaLabel = useMemo(() => {
    const version = String(state.latestVersion ?? "").trim();
    if (state.status === "downloaded") return t("topbarUpdate.installAria");
    if (state.status === "downloading") return t("topbarUpdate.downloadingAria", { percent: progressPercent });
    return version ? t("topbarUpdate.availableVersionAria", { version }) : t("topbarUpdate.availableAria");
  }, [progressPercent, state.latestVersion, state.status, t]);

  async function onClick() {
    if (actionRunning || state.status === "downloading") return;
    setActionRunning(true);
    try {
      if (state.status === "downloaded") {
        await codexDesktop.app.installUpdate();
        return;
      }
      if (state.status === "available") {
        setState(await codexDesktop.app.downloadUpdate());
      }
    } finally {
      setActionRunning(false);
    }
  }

  if (!visible) return null;

  const NoticeIcon = state.status === "downloaded" ? RotateCcw : state.status === "downloading" ? LoaderCircle : Download;

  return (
    <button
      className={[
        "topbar-update-notice",
        state.status === "downloading" ? "is-downloading" : "",
        state.status === "downloaded" ? "is-downloaded" : "",
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      type="button"
      disabled={actionRunning || state.status === "downloading"}
      aria-label={ariaLabel}
      onClick={() => void onClick()}
    >
      <NoticeIcon className="topbar-update-notice__icon" aria-hidden="true" />
      <span className="topbar-update-notice__text" aria-live="polite">
        {label}
      </span>
    </button>
  );
}

// packages/app/src/renderer/components/layout/topbar/TopBarUpdateNotice.vue
<template>
  <Transition name="topbar-update-slide">
    <button
      v-if="visible"
      class="topbar-update-notice"
      :class="{
        'is-downloading': updateState.status === 'downloading',
        'is-downloaded': updateState.status === 'downloaded',
      }"
      type="button"
      :disabled="actionDisabled"
      :aria-label="ariaLabel"
      @click="onClick"
    >
      <component :is="noticeIcon" class="topbar-update-notice__icon" aria-hidden="true" />
      <span class="topbar-update-notice__text" aria-live="polite">{{ label }}</span>
    </button>
  </Transition>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { Download, LoaderCircle, RotateCcw } from "lucide-vue-next";
import { useAppShellStore } from "../../../stores/appShell.store";
import { codexDesktop } from "../../../api/codexDesktopClient";
import type { AppUpdateSnapshot } from "@codenexus/shared/ipc/contracts";

const { t } = useI18n();

const DEFAULT_STATE: AppUpdateSnapshot = {
  status: "idle",
  currentVersion: "0.0.0",
  latestVersion: null,
  releaseName: null,
  releaseNotes: null,
  updateAvailable: false,
  downloaded: false,
  progress: null,
  errorMessage: null,
  checkedAt: null,
  isPackaged: false,
};

const updateState = reactive<AppUpdateSnapshot>({ ...DEFAULT_STATE });
const actionRunning = ref(false);
let offUpdateState: (() => void) | null = null;

const applyState = (next: AppUpdateSnapshot) => {
  Object.assign(updateState, next);
};

const visible = computed(
  () =>
    updateState.status === "available" || updateState.status === "downloading" || updateState.status === "downloaded"
);

const progressPercent = computed(() => {
  const percent = Number(updateState.progress?.percent ?? 0);
  if (!Number.isFinite(percent)) return 0;
  return Math.max(0, Math.min(100, Math.round(percent)));
});

const label = computed(() => {
  if (updateState.status === "downloading") {
    return t("topbarUpdate.downloading", { percent: progressPercent.value });
  }
  if (updateState.status === "downloaded") return t("topbarUpdate.install");
  return t("topbarUpdate.available");
});

const ariaLabel = computed(() => {
  const version = String(updateState.latestVersion ?? "").trim();
  if (updateState.status === "downloaded") return t("topbarUpdate.installAria");
  if (updateState.status === "downloading") {
    return t("topbarUpdate.downloadingAria", { percent: progressPercent.value });
  }
  return version ? t("topbarUpdate.availableVersionAria", { version }) : t("topbarUpdate.availableAria");
});

const noticeIcon = computed(() => {
  if (updateState.status === "downloaded") return RotateCcw;
  if (updateState.status === "downloading") return LoaderCircle;
  return Download;
});

const actionDisabled = computed(() => actionRunning.value || updateState.status === "downloading");

async function onClick() {
  if (actionDisabled.value) return;
  actionRunning.value = true;
  try {
    if (updateState.status === "downloaded") {
      await codexDesktop.app.installUpdate();
      return;
    }
    if (updateState.status === "available") {
      applyState(await codexDesktop.app.downloadUpdate());
    }
  } catch {
    useAppShellStore().openSettings("update");
  } finally {
    actionRunning.value = false;
  }
}

onMounted(async () => {
  offUpdateState = codexDesktop.app.onUpdateState(applyState);
  applyState(await codexDesktop.app.getUpdateState());
});

onBeforeUnmount(() => {
  offUpdateState?.();
  offUpdateState = null;
});
</script>
