// packages/app/src/renderer/components/layout/chat/ChatRowRenderer.tsx
import type { TimelineEventItem } from "../../../domain/types";
import { stripInlineMemoryCitation } from "../../../domain/taggedMessageBlocks";
import { tryParseStructuredFinalAnswerV1 } from "../../../domain/structuredFinalAnswer";
import { renderMarkdownToSafeHtml } from "../../../features/timeline/markdownRenderer";
import { formatTime } from "../../../features/timeline/renderModel/formatters";
import type { ChatInlineRewriteDraft, ChatRenderedRow, PlanDeltaExecUiState } from "../types/chat.types";
import type { SandboxMode } from "../../../stores/runtime.store";
import ChatActivityRow from "../../chat/ChatActivityRow";
import ChatAssistantMessage from "../../chat/ChatAssistantMessage";
import ChatAuxActivityGroup from "../../chat/ChatAuxActivityGroup";
import ChatCommandActionRow from "../../chat/ChatCommandActionRow";
import ChatCommandSessionCard from "../../chat/ChatCommandSessionCard";
import ChatImageToolCard from "../../chat/ChatImageToolCard";
import ChatReasoningBlock from "../../chat/ChatReasoningBlock";
import ChatSshToolActivity from "../../chat/ChatSshToolActivity";
import ChatSystemRow from "../../chat/ChatSystemRow";
import ChatTokenUsageSummary from "../../chat/ChatTokenUsageSummary";
import ChatUserMessage from "../../chat/ChatUserMessage";
import ChatWebSearchCard from "../../chat/ChatWebSearchCard";
import AgentMarkdownContent from "../../ui/AgentMarkdownContent";
import DynamicToolCallCardContent from "../../timeline/cards/DynamicToolCallCardContent";
import FileChangeCardContent from "../../timeline/cards/FileChangeCardContent";
import McpResourceReadCardContent from "../../timeline/cards/McpResourceReadCardContent";
import McpToolCardContent from "../../timeline/cards/McpToolCardContent";
import CommandReadActivityRow from "../../timeline/activities/CommandReadActivityRow";
import CommandListActivityRow from "../../timeline/activities/CommandListActivityRow";
import CommandSearchActivityRow from "../../timeline/activities/CommandSearchActivityRow";
import { CHAT_ROW_ACTIVITY_CLASS, CHAT_ROW_TOOL_CLASS } from "./chatPresentation";
import { chatActivityToneClass } from "./chatStyle";

export type ChatRowRendererProps = {
  renderedRow?: ChatRenderedRow;
  workspaceRoot?: string;
  viewPrefs?: { showTimestamps?: boolean };
  planExecStateByEventId?: Record<string, PlanDeltaExecUiState>;
  isTurnRunning?: boolean;
  modelOptions?: readonly (string | { value: string; label: string; disabled?: boolean })[];
  reasoningEffortOptions?: readonly (string | { value: string; label: string; disabled?: boolean })[];
  sandboxModeOptions?: readonly (string | { value: string; label: string; disabled?: boolean })[];
  sendDisabled?: boolean;
  inlineRewriteDraft?: ChatInlineRewriteDraft | null;
  userMessageParts?: (event: TimelineEventItem) => any[];
  userMessageImageCount?: (event: TimelineEventItem) => number;
  visibleUserMessageImageEntries?: (event: TimelineEventItem) => any[];
  visibleImageToolEntries?: (item: any) => any[];
  handleThumbLoadError?: (payload: any) => void;
  handleUserFileTokenClick?: (path: string) => void;
  handleUserBubbleClick?: (event: TimelineEventItem) => void;
  updateInlineRewriteDraft?: (patch: Partial<ChatInlineRewriteDraft>) => void;
  closeInlineRewrite?: () => void;
  sendInlineRewriteDraft?: () => void;
  executePlanFromPlanDelta?: (event: TimelineEventItem) => void;
  updatePlanExecModel?: (eventId: string, value: string) => void;
  updatePlanExecReasoningEffort?: (eventId: string, value: string) => void;
  updatePlanExecSandboxMode?: (eventId: string, value: SandboxMode) => void;
  handlePreviewImage?: (payload: any) => void;
  handleLayoutChange?: () => void;
  getMarkdownEventHtml?: (event: TimelineEventItem) => string;
  isReasoningOpen?: (item: any) => boolean;
  setReasoningOpen?: (item: any, open: boolean) => void;
  isCommandFilesOpen?: (nodeId: string) => boolean;
  toggleCommandFilesOpen?: (nodeId: string) => void;
  isCommandSessionStopping?: (processId: string) => boolean;
  stopCommandSession?: (item: any) => void;
  isMcpToolGroupOpen?: (id: string) => boolean;
  onMcpToolGroupToggle?: (id: string, open: boolean) => void;
  isMcpResourceOpen?: (id: string) => boolean;
  setMcpResourceOpen?: (id: string, open: boolean) => void;
  openMcpResourceInPanel?: (item: any) => void;
  onOpenRelatedMcpResource?: (item: any) => void;
};

function markdownHtml(event: TimelineEventItem, getMarkdownEventHtml?: (event: TimelineEventItem) => string) {
  if (getMarkdownEventHtml) return getMarkdownEventHtml(event);
  return renderMarkdownToSafeHtml(String(event.paramsText ?? ""), { cache: true });
}

function GenericToolCard({ title, item }: { title: string; item: any }) {
  const body = (() => {
    try {
      return JSON.stringify(item ?? {}, null, 2);
    } catch {
      return String(item ?? "");
    }
  })();
  return (
    <div className={CHAT_ROW_TOOL_CLASS}>
      <div className="chat-tool-wrap w-full max-w-full min-w-0">
        <div className="dynamic-tool-chat-card rounded border border-[var(--ui-code-border)] bg-[var(--ui-code-bg)] p-3 text-xs">
          <div className="mb-2 font-semibold">{title}</div>
          <pre className="app-scrollbar m-0 max-h-64 overflow-auto whitespace-pre-wrap">{body}</pre>
        </div>
      </div>
    </div>
  );
}

export default function ChatRowRenderer(props: ChatRowRendererProps) {
  const row = props.renderedRow;
  if (!row) return null;

  if (row.kind === "user") {
    return (
      <ChatUserMessage
        event={row.event}
        workspaceRoot={props.workspaceRoot}
        messageParts={props.userMessageParts?.(row.event)}
        imageCount={props.userMessageImageCount?.(row.event)}
        visibleImages={props.visibleUserMessageImageEntries?.(row.event)}
        showTimestamps={Boolean(props.viewPrefs?.showTimestamps)}
        formattedTime={new Date(row.event.createdAt).toLocaleTimeString()}
        onClick={() => props.handleUserBubbleClick?.(row.event)}
        onFileTokenClick={props.handleUserFileTokenClick}
        onThumbLoadError={props.handleThumbLoadError}
        onPreviewImage={props.handlePreviewImage}
        inlineRewriteDraft={props.inlineRewriteDraft?.anchorEventId === String(row.event.id ?? "") ? props.inlineRewriteDraft : null}
        modelOptions={props.modelOptions}
        reasoningEffortOptions={props.reasoningEffortOptions}
        sandboxModeOptions={props.sandboxModeOptions}
        sendDisabled={props.sendDisabled}
        onInlineRewriteUpdate={props.updateInlineRewriteDraft}
        onInlineRewriteCancel={props.closeInlineRewrite}
        onInlineRewriteSend={props.sendInlineRewriteDraft}
      />
    );
  }
  if (row.kind === "assistant") {
    const text = stripInlineMemoryCitation(String(row.event.paramsText ?? ""));
    return (
      <ChatAssistantMessage
        event={row.event}
        markdownHtml={markdownHtml(row.event, props.getMarkdownEventHtml)}
        isStructuredFinalAnswer={Boolean(tryParseStructuredFinalAnswerV1(text))}
        execState={props.planExecStateByEventId?.[String(row.event.id ?? "")] ?? null}
        modelOptions={props.modelOptions}
        isTurnRunning={props.isTurnRunning}
        reasoningEffortOptions={props.reasoningEffortOptions}
        sandboxModeOptions={props.sandboxModeOptions}
        onExecutePlan={props.executePlanFromPlanDelta}
        onUpdateModel={(value) => props.updatePlanExecModel?.(String(row.event.id ?? ""), value)}
        onUpdateReasoningEffort={(value) => props.updatePlanExecReasoningEffort?.(String(row.event.id ?? ""), value)}
        onUpdateSandboxMode={(value) => props.updatePlanExecSandboxMode?.(String(row.event.id ?? ""), value)}
      />
    );
  }
  if (row.kind === "system") return <ChatSystemRow text={row.text} />;
  if (row.kind === "activity") {
    return <ChatActivityRow text={row.text} activityDotClass={chatActivityToneClass(row.tone)} />;
  }
  if (row.kind === "assistantCommentary") {
    return (
      <div className={CHAT_ROW_ACTIVITY_CLASS}>
        <AgentMarkdownContent className="chat-assistant-commentary min-w-0" html={markdownHtml(row.event, props.getMarkdownEventHtml)} />
      </div>
    );
  }
  if (row.kind === "auxActivityGroup") {
    return (
      <ChatAuxActivityGroup
        id={row.id}
        items={row.items}
        summaryItems={row.summaryItems}
        summaryText={row.summaryText}
        status={row.status}
        defaultCollapsed={row.defaultCollapsed}
        startedAtMs={row.startedAtMs}
        answerStartedAtMs={row.answerStartedAtMs}
        elapsedLive={row.elapsedLive}
        onLayoutChange={props.handleLayoutChange}
      >
        {({ item }: any) => <ChatRowRenderer {...props} renderedRow={item} />}
      </ChatAuxActivityGroup>
    );
  }
  if (row.kind === "tokenUsageSummary") return <ChatTokenUsageSummary usage={row.item.usage} onLayoutChange={props.handleLayoutChange} />;
  if (row.kind === "imageTool") {
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <ChatImageToolCard
          item={row.item}
          visibleImages={props.visibleImageToolEntries?.(row.item)}
          workspaceRoot={props.workspaceRoot}
          showTimestamps={Boolean(props.viewPrefs?.showTimestamps)}
          formattedTime={formatTime(row.createdAt)}
          onLoadError={props.handleThumbLoadError}
          onPreview={props.handlePreviewImage}
        />
      </div>
    );
  }
  if (row.kind === "webSearch") {
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <ChatWebSearchCard item={row.item} />
      </div>
    );
  }
  if (row.kind === "reasoningBlock") {
    return (
      <ChatReasoningBlock
        isOpen={props.isReasoningOpen?.(row.item)}
        summaryTitle={row.item.title || undefined}
        durationText={row.item.durationMs ? `${Math.max(1, Math.round(row.item.durationMs / 1000))}s` : ""}
        rawText={row.item.rawText}
        html={renderMarkdownToSafeHtml(String(row.item.text ?? row.item.rawText ?? ""), { cache: true })}
        rawContentCount={row.item.rawContentCount}
        onToggle={(open) => props.setReasoningOpen?.(row.item, open)}
      />
    );
  }
  if (row.kind === "dynamicTool") {
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <div className="chat-tool-wrap w-full max-w-full min-w-0">
          <DynamicToolCallCardContent className="dynamic-tool-chat-card w-full rounded-xl border border-[var(--ui-code-border)] bg-[var(--ui-code-bg)] p-3" item={row.item} />
        </div>
      </div>
    );
  }
  if (row.kind === "fileChange") {
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <div className="chat-tool-wrap w-full max-w-full min-w-0">
          <FileChangeCardContent item={row.item} mode="chat" wrapDiffLines={false} onLayoutChange={props.handleLayoutChange} />
        </div>
      </div>
    );
  }
  if (row.kind === "commandAction") {
    return (
      <ChatCommandActionRow
        item={row.item}
        isFilesOpen={props.isCommandFilesOpen?.(row.item.id)}
        onToggleFiles={() => props.toggleCommandFilesOpen?.(row.item.id)}
      />
    );
  }
  if (row.kind === "commandSession") {
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <ChatCommandSessionCard
          item={row.item}
          stopping={props.isCommandSessionStopping?.(row.item.processId)}
          onStop={props.stopCommandSession}
          onLayoutChange={props.handleLayoutChange}
        />
      </div>
    );
  }
  if (row.kind === "commandRead") return <CommandReadActivityRow item={row.item} />;
  if (row.kind === "commandList") return <CommandListActivityRow item={row.item} />;
  if (row.kind === "commandSearch") return <CommandSearchActivityRow item={row.item} />;
  if (row.kind === "mcpResourceRead") {
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <div className="chat-tool-wrap w-full max-w-full min-w-0">
          <McpResourceReadCardContent
            open={props.isMcpResourceOpen?.(row.item.id)}
            item={row.item}
            onOpenInPanel={props.openMcpResourceInPanel}
            onOpenChange={(open: boolean) => props.setMcpResourceOpen?.(row.item.id, open)}
          />
        </div>
      </div>
    );
  }
  if (row.kind === "mcpToolGroup") {
    const isSsh = (row.group.items ?? []).some((item: any) => String(item?.server ?? "").toLowerCase().includes("ssh"));
    if (isSsh) return <ChatSshToolActivity group={row.group} className={CHAT_ROW_TOOL_CLASS} />;
    return (
      <div className={CHAT_ROW_TOOL_CLASS}>
        <div className="chat-tool-wrap w-full max-w-full min-w-0">
          <McpToolCardContent
            open={props.isMcpToolGroupOpen?.(row.group.id)}
            group={row.group}
            items={row.group.items}
            onOpenRelatedResource={props.onOpenRelatedMcpResource}
            onOpenChange={(open: boolean) => props.onMcpToolGroupToggle?.(row.group.id, open)}
          />
        </div>
      </div>
    );
  }
  return <GenericToolCard title={String((row as any).kind ?? "Tool")} item={row} />;
}

// packages/app/src/renderer/components/layout/chat/ChatRowRenderer.vue
<template>
  <ChatUserMessage
    v-if="renderedRow.kind === 'user'"
    :event="renderedRow.event"
    :workspaceRoot="workspaceRoot"
    :messageParts="userMessageParts(renderedRow.event)"
    :imageCount="userMessageImageCount(renderedRow.event)"
    :visibleImages="visibleUserMessageImageEntries(renderedRow.event)"
    :showTimestamps="viewPrefs.showTimestamps"
    :formattedTime="formatTime(renderedRow.event.createdAt)"
    :inlineRewriteDraft="inlineRewriteDraft?.anchorEventId === renderedRow.event.id ? inlineRewriteDraft : null"
    :modelOptions="modelOptions"
    :reasoningEffortOptions="reasoningEffortOptions"
    :sandboxModeOptions="sandboxModeOptions"
    :sendDisabled="isTurnRunning"
    @click="handleUserBubbleClick"
    @file-token-click="handleUserFileTokenClick"
    @thumb-load-error="handleThumbLoadError"
    @preview-image="handlePreviewImage"
    @inline-rewrite-update="onInlineRewriteUpdate?.($event)"
    @inline-rewrite-cancel="onInlineRewriteCancel?.()"
    @inline-rewrite-send="onInlineRewriteSend?.()"
  />

  <ChatAssistantMessage
    v-else-if="renderedRow.kind === 'assistant'"
    :event="renderedRow.event"
    :isStructuredFinalAnswer="isStructuredFinalAnswerEvent(renderedRow.event)"
    :markdownHtml="assistantMarkdownHtml(renderedRow.event)"
    :execState="planExecStateByEventId[renderedRow.event.id] ?? null"
    :modelOptions="modelOptions"
    :isTurnRunning="isTurnRunning"
    :reasoningEffortOptions="reasoningEffortOptions"
    :sandboxModeOptions="sandboxModeOptions"
    @execute-plan="executePlanFromPlanDelta"
    @update:model="(value) => updatePlanExecModel(renderedRow.event.id, value)"
    @update:reasoning-effort="(value) => updatePlanExecReasoningEffort(renderedRow.event.id, value)"
    @update:sandbox-mode="(value) => updatePlanExecSandboxMode(renderedRow.event.id, value)"
  />

  <ChatSystemRow v-else-if="renderedRow.kind === 'system'" :text="renderedRow.text" />

  <ChatAuxActivityGroup
    v-else-if="renderedRow.kind === 'auxActivityGroup'"
    :id="renderedRow.id"
    :workspace-root="workspaceRoot"
    :items="renderedRow.items"
    :summaryItems="renderedRow.summaryItems"
    :summaryText="renderedRow.summaryText"
    :status="renderedRow.status"
    :defaultCollapsed="renderedRow.defaultCollapsed"
    :startedAtMs="renderedRow.startedAtMs"
    :answerStartedAtMs="renderedRow.answerStartedAtMs"
    :elapsedLive="renderedRow.elapsedLive"
    @layout-change="handleLayoutChange?.()"
  >
    <template #default="{ item }">
      <ChatRowRenderer
        :renderedRow="item"
        :workspaceRoot="workspaceRoot"
        :viewPrefs="viewPrefs"
        :planExecStateByEventId="planExecStateByEventId"
        :modelOptions="modelOptions"
        :isTurnRunning="isTurnRunning"
        :reasoningEffortOptions="reasoningEffortOptions"
        :sandboxModeOptions="sandboxModeOptions"
        :userMessageParts="userMessageParts"
        :userMessageImageCount="userMessageImageCount"
        :visibleUserMessageImageEntries="visibleUserMessageImageEntries"
        :visibleImageToolEntries="visibleImageToolEntries"
        :handleThumbLoadError="handleThumbLoadError"
        :handleUserFileTokenClick="handleUserFileTokenClick"
        :handleUserBubbleClick="handleUserBubbleClick"
        :handlePreviewImage="handlePreviewImage"
        :handleLayoutChange="handleLayoutChange"
        :getMarkdownEventHtml="getMarkdownEventHtml"
        :isReasoningOpen="isReasoningOpen"
        :setReasoningOpen="setReasoningOpen"
        :isCommandFilesOpen="isCommandFilesOpen"
        :toggleCommandFilesOpen="toggleCommandFilesOpen"
        :isCommandSessionStopping="isCommandSessionStopping"
        :stopCommandSession="stopCommandSession"
        :isMcpToolGroupOpen="isMcpToolGroupOpen"
        :onMcpToolGroupToggle="onMcpToolGroupToggle"
        :isMcpToolItemDetailOpen="isMcpToolItemDetailOpen"
        :onMcpToolItemDetailToggle="onMcpToolItemDetailToggle"
        :isMcpResourceOpen="isMcpResourceOpen"
        :setMcpResourceOpen="setMcpResourceOpen"
        :openMcpResourceInPanel="openMcpResourceInPanel"
        :onOpenRelatedMcpResource="onOpenRelatedMcpResource"
        :executePlanFromPlanDelta="executePlanFromPlanDelta"
        :updatePlanExecModel="updatePlanExecModel"
        :updatePlanExecReasoningEffort="updatePlanExecReasoningEffort"
        :updatePlanExecSandboxMode="updatePlanExecSandboxMode"
        :inlineRewriteDraft="inlineRewriteDraft"
        :onInlineRewriteUpdate="onInlineRewriteUpdate"
        :onInlineRewriteCancel="onInlineRewriteCancel"
        :onInlineRewriteSend="onInlineRewriteSend"
      />
    </template>
  </ChatAuxActivityGroup>

  <ChatActivityRow
    v-else-if="renderedRow.kind === 'activity'"
    :text="renderedRow.text"
    :activityDotClass="activityDotClass(renderedRow.tone)"
  />

  <div v-else-if="renderedRow.kind === 'assistantCommentary'" :class="CHAT_ROW_ACTIVITY_CLASS">
    <AgentMarkdownContent
      class="chat-assistant-commentary agent-markdown-body min-w-0"
      :html="assistantMarkdownHtml(renderedRow.event)"
    />
  </div>

  <ChatTokenUsageSummary
    v-else-if="renderedRow.kind === 'tokenUsageSummary'"
    :usage="(renderedRow as any).item.usage"
    @layout-change="handleLayoutChange?.()"
  />

  <ChatImageToolCard
    v-else-if="renderedRow.kind === 'imageTool'"
    :item="(renderedRow as any).item"
    :visibleImages="visibleImageToolEntries((renderedRow as any).item)"
    :showTimestamps="viewPrefs.showTimestamps"
    :formattedTime="formatTime((renderedRow as any).createdAt)"
    :workspaceRoot="workspaceRoot"
    @load-error="handleThumbLoadError"
    @preview="handlePreviewImage($event)"
    :class="CHAT_ROW_TOOL_CLASS"
  />

  <ChatWebSearchCard
    v-else-if="renderedRow.kind === 'webSearch'"
    :item="(renderedRow as any).item"
    :class="CHAT_ROW_TOOL_CLASS"
  />

  <div v-else-if="renderedRow.kind === 'dynamicTool'" :class="CHAT_ROW_TOOL_CLASS">
    <div class="chat-tool-wrap w-full max-w-full min-w-0">
      <DynamicToolCallCardContent
        class="dynamic-tool-chat-card w-full rounded-xl border border-[var(--ui-code-border)] bg-[var(--ui-code-bg)] p-3"
        :item="(renderedRow as any).item"
      />
    </div>
  </div>

  <ChatReasoningBlock
    v-else-if="renderedRow.kind === 'reasoningBlock'"
    :isOpen="isReasoningOpen((renderedRow as any).item)"
    :summaryTitle="(renderedRow as any).item.title || t('chat.reasoning')"
    :durationText="reasoningDurationText((renderedRow as any).item.durationMs)"
    :html="toReasoningHtml((renderedRow as any).item.text)"
    :rawText="(renderedRow as any).item.rawText"
    :rawContentCount="(renderedRow as any).item.rawContentCount"
    @toggle="(next) => setReasoningOpen((renderedRow as any).item, next)"
  />

  <div v-else-if="renderedRow.kind === 'fileChange'" :class="CHAT_ROW_TOOL_CLASS">
    <div class="chat-tool-wrap w-full max-w-full min-w-0">
      <FileChangeCardContent
        :item="(renderedRow as any).item"
        mode="chat"
        :wrapDiffLines="false"
        @layout-change="handleLayoutChange?.()"
      />
    </div>
  </div>

  <ChatCommandActionRow
    v-else-if="renderedRow.kind === 'commandAction'"
    :item="(renderedRow as any).item"
    :isFilesOpen="isCommandFilesOpen((renderedRow as any).item.id)"
    :renderLimit="COMMAND_FILES_RENDER_LIMIT"
    @toggle-files="toggleCommandFilesOpen((renderedRow as any).item.id)"
    :class="CHAT_ROW_ACTIVITY_CLASS"
  />

  <div v-else-if="renderedRow.kind === 'commandSession'" :class="CHAT_ROW_TOOL_CLASS">
    <ChatCommandSessionCard
      :item="(renderedRow as any).item"
      :stopping="isCommandSessionStopping((renderedRow as any).item.processId)"
      @stop="stopCommandSession"
      @layout-change="handleLayoutChange?.()"
    />
  </div>

  <div v-else-if="renderedRow.kind === 'commandRead'" :class="CHAT_ROW_TOOL_CLASS">
    <CommandReadActivityRow :item="(renderedRow as any).item" />
  </div>

  <div v-else-if="renderedRow.kind === 'commandList'" :class="CHAT_ROW_TOOL_CLASS">
    <CommandListActivityRow :item="(renderedRow as any).item" />
  </div>

  <div v-else-if="renderedRow.kind === 'commandSearch'" :class="CHAT_ROW_TOOL_CLASS">
    <CommandSearchActivityRow :item="(renderedRow as any).item" />
  </div>

  <div v-else-if="renderedRow.kind === 'mcpResourceRead'" :class="CHAT_ROW_TOOL_CLASS">
    <div class="chat-tool-wrap w-full max-w-full min-w-0">
      <McpResourceReadCardContent
        :open="isMcpResourceOpen((renderedRow as any).item.id)"
        :item="(renderedRow as any).item"
        :onOpenInPanel="openMcpResourceInPanel"
        @update:open="setMcpResourceOpen((renderedRow as any).item.id, $event)"
      />
    </div>
  </div>

  <div v-else-if="renderedRow.kind === 'mcpToolGroup'" :class="CHAT_ROW_TOOL_CLASS">
    <ChatSshToolActivity v-if="isSshMcpToolGroup((renderedRow as any).group)" :group="(renderedRow as any).group" />
    <div v-else class="chat-tool-wrap w-full max-w-full min-w-0">
      <McpToolCardContent
        :open="isMcpToolGroupOpen((renderedRow as any).group.id)"
        :tagText="mcpToolGroupTagText((renderedRow as any).group)"
        :groupClass="`${mcpToolGroupClass((renderedRow as any).group)} opacity-[0.96]`"
        :summaryText="mcpToolGroupSummaryText((renderedRow as any).group)"
        :statsText="mcpToolGroupStatsText((renderedRow as any).group)"
        :items="(renderedRow as any).group.items"
        :itemClass="mcpToolItemClass as any"
        :itemStatusText="mcpToolItemStatusText as any"
        :itemMetricsText="mcpToolItemMetricsText as any"
        :itemTitle="mcpToolItemTitle as any"
        :itemMetaText="mcpToolItemMetaText as any"
        :isDetailOpen="isMcpToolItemDetailOpen"
        :onDetailToggle="onMcpToolItemDetailToggle"
        :onOpenRelatedResource="onOpenRelatedMcpResource"
        @update:open="onMcpToolGroupToggle((renderedRow as any).group.id, $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useI18n } from "vue-i18n";
import ChatUserMessage from "../../chat/ChatUserMessage.vue";
import ChatAssistantMessage from "../../chat/ChatAssistantMessage.vue";
import ChatActivityRow from "../../chat/ChatActivityRow.vue";
import ChatAuxActivityGroup from "../../chat/ChatAuxActivityGroup.vue";
import ChatReasoningBlock from "../../chat/ChatReasoningBlock.vue";
import ChatSystemRow from "../../chat/ChatSystemRow.vue";
import ChatImageToolCard from "../../chat/ChatImageToolCard.vue";
import ChatWebSearchCard from "../../chat/ChatWebSearchCard.vue";
import ChatSshToolActivity from "../../chat/ChatSshToolActivity.vue";
import ChatTokenUsageSummary from "../../chat/ChatTokenUsageSummary.vue";
import ChatCommandActionRow from "../../chat/ChatCommandActionRow.vue";
import ChatCommandSessionCard from "../../chat/ChatCommandSessionCard.vue";
import AgentMarkdownContent from "../../ui/AgentMarkdownContent.vue";
import DynamicToolCallCardContent from "../../timeline/cards/DynamicToolCallCardContent.vue";
import FileChangeCardContent from "../../timeline/cards/FileChangeCardContent.vue";
import McpResourceReadCardContent from "../../timeline/cards/McpResourceReadCardContent.vue";
import McpToolCardContent from "../../timeline/cards/McpToolCardContent.vue";
import CommandReadActivityRow from "../../timeline/activities/CommandReadActivityRow.vue";
import CommandListActivityRow from "../../timeline/activities/CommandListActivityRow.vue";
import CommandSearchActivityRow from "../../timeline/activities/CommandSearchActivityRow.vue";
import { CHAT_ROW_ACTIVITY_CLASS, CHAT_ROW_TOOL_CLASS } from "./chatPresentation";
import { chatActivityToneClass } from "./chatStyle";

import type { TimelineEventItem } from "../../../domain/types";
import { tryParseStructuredFinalAnswerV1 } from "../../../domain/structuredFinalAnswer";
import { stripInlineMemoryCitation } from "../../../domain/taggedMessageBlocks";
import { renderMarkdownToSafeHtml } from "../../../features/timeline/markdownRenderer";
import { useMarkdownRendererRefresh } from "../../../features/timeline/useMarkdownRendererRefresh";
import type {
  CommandSessionNode,
  McpResourceReadNode,
  McpToolGroupNode,
} from "../../../features/timeline/renderModel/buildTimelineNodes";
import {
  formatTime,
  mcpToolGroupClass,
  mcpToolGroupStatsText,
  mcpToolGroupSummaryText,
  mcpToolGroupTagText,
  mcpToolItemClass,
  mcpToolItemMetaText,
  mcpToolItemMetricsText,
  mcpToolItemStatusText,
  mcpToolItemTitle,
} from "../../../features/timeline/renderModel/formatters";
import type { SandboxMode } from "../../../stores/runtime.store";
import type { McpToolItem } from "../../timeline/cards/McpToolCardContent.vue";
import type {
  ChatImageEntry,
  ChatInlineRewriteDraft,
  ChatRenderedRow,
  ChatUserMessagePart,
  ImagePreviewPayload,
  PlanDeltaExecUiState,
  ThumbLoadErrorPayload,
} from "../types/chat.types";

defineOptions({ name: "ChatRowRenderer" });

type OptionInput = string | { value: string; label: string; disabled?: boolean };
type AnyFn = (...args: any[]) => any;

const COMMAND_FILES_RENDER_LIMIT = 1000;
const { markdownRendererTick, refreshWhenReady } = useMarkdownRendererRefresh();
const { t } = useI18n();

const isSshMcpToolGroup = (group: McpToolGroupNode | null | undefined): boolean => {
  return (group?.items ?? []).some((item) => {
    const server = String(item?.server ?? "")
      .trim()
      .toLowerCase();
    return server.includes("ssh");
  });
};

const props = defineProps<{
  renderedRow: ChatRenderedRow;
  workspaceRoot: string;
  viewPrefs: { showTimestamps: boolean };
  planExecStateByEventId: Record<string, PlanDeltaExecUiState | undefined>;
  modelOptions: readonly OptionInput[];
  isTurnRunning: boolean;
  reasoningEffortOptions: readonly OptionInput[];
  sandboxModeOptions: readonly OptionInput[];
  userMessageParts: (event: TimelineEventItem) => ChatUserMessagePart[];
  userMessageImageCount: (event: TimelineEventItem) => number;
  visibleUserMessageImageEntries: (event: TimelineEventItem) => ChatImageEntry[];
  visibleImageToolEntries: AnyFn;
  handleThumbLoadError: (err: ThumbLoadErrorPayload) => void;
  handleUserFileTokenClick: (path: string) => void;
  handleUserBubbleClick: (event: TimelineEventItem) => void;
  handlePreviewImage: (payload: ImagePreviewPayload) => void;
  handleLayoutChange?: () => void;
  getMarkdownEventHtml: (event: TimelineEventItem) => string;
  isReasoningOpen: AnyFn;
  setReasoningOpen: AnyFn;
  isCommandFilesOpen: (nodeId: string) => boolean;
  toggleCommandFilesOpen: (nodeId: string) => void;
  isCommandSessionStopping: (processId: string) => boolean;
  stopCommandSession: (item: CommandSessionNode) => void;
  isMcpToolGroupOpen: (id: string) => boolean;
  onMcpToolGroupToggle: (id: string, open: boolean) => void;
  isMcpToolItemDetailOpen: AnyFn;
  onMcpToolItemDetailToggle: AnyFn;
  isMcpResourceOpen: (id: string) => boolean;
  setMcpResourceOpen: (id: string, open: boolean) => void;
  openMcpResourceInPanel: (item: Pick<McpResourceReadNode, "server" | "uri" | "sourceTab" | "templateKey">) => void;
  onOpenRelatedMcpResource: (item: McpToolItem) => void;
  executePlanFromPlanDelta: (event: TimelineEventItem) => void;
  updatePlanExecModel: (eventId: string, value: string) => void;
  updatePlanExecReasoningEffort: (eventId: string, value: string) => void;
  updatePlanExecSandboxMode: (eventId: string, value: SandboxMode) => void;
  inlineRewriteDraft?: ChatInlineRewriteDraft | null;
  onInlineRewriteUpdate?: (patch: Partial<ChatInlineRewriteDraft>) => void;
  onInlineRewriteCancel?: () => void;
  onInlineRewriteSend?: () => void;
}>();

const reasoningDurationText = (durationMs: number | null | undefined) => {
  if (durationMs == null) return "";
  return `${Math.max(1, Math.round(durationMs / 1000))}s`;
};

const toReasoningHtml = (text: string) => {
  const source = String(text ?? "").trim();
  if (!source) return `<p>${t("chat.emptyContent")}</p>`;
  void markdownRendererTick.value;
  const html = renderMarkdownToSafeHtml(source);
  refreshWhenReady();
  return html;
};

const activityDotClass = chatActivityToneClass;
const isStructuredFinalAnswerEvent = (event: TimelineEventItem): boolean => {
  if (event.method === "item/plan/delta") return false;
  return Boolean(tryParseStructuredFinalAnswerV1(stripInlineMemoryCitation(event.paramsText)));
};

const assistantMarkdownHtml = (event: TimelineEventItem): string => {
  if (event.method === "item/plan/delta") return "";
  if (isStructuredFinalAnswerEvent(event)) return "";
  return props.getMarkdownEventHtml(event);
};
</script>

<style scoped>
.chat-async-card-loading {
  display: grid;
  min-height: 44px;
  width: 100%;
  gap: 8px;
  border: 1px solid color-mix(in srgb, var(--border) 68%, transparent);
  border-radius: 8px;
  background: color-mix(in srgb, var(--surface-1) 72%, transparent);
  padding: 10px;
}

.chat-async-card-loading__line {
  height: 8px;
  border-radius: 999px;
  background: color-mix(in srgb, var(--text-muted) 18%, transparent);
}

.chat-async-card-loading__line--wide {
  width: min(260px, 72%);
}

.chat-async-card-loading__line--short {
  width: min(160px, 46%);
}
</style>
