// packages/app/src/renderer/components/layout/SettingsPage.vue
<template>
  <section class="settings-page" :aria-label="t('settings.pageAria')">
    <div class="settings-workspace">
      <aside class="settings-sidebar app-scrollbar" :aria-label="t('settings.sidebarAria')">
        <nav class="settings-nav" role="tablist" :aria-label="t('settings.tabsAria')">
          <section v-for="group in tabGroups" :key="group.label" class="settings-nav-group">
            <div class="settings-nav-section">{{ group.label }}</div>
            <button
              v-for="tab in group.items"
              :key="tab.key"
              class="settings-nav-item"
              :class="{ 'is-active': activeTab === tab.key }"
              type="button"
              role="tab"
              :aria-selected="activeTab === tab.key ? 'true' : 'false'"
              @click="appShellStore.setSettingsTab(tab.key)"
            >
              <component :is="tab.icon" class="settings-nav-icon" aria-hidden="true" />
              <span class="settings-nav-copy">
                <span class="settings-nav-label">{{ tab.label }}</span>
                <span class="settings-nav-desc">{{ tab.desc }}</span>
              </span>
            </button>
          </section>
        </nav>
      </aside>

      <div class="settings-scroll app-scrollbar">
        <div class="settings-stage">
          <div class="settings-tab-content" :data-tab="activeTab">
            <GlobalConfigDrawer v-if="activeTab === 'global'" mode="settings" />
            <SettingsModelProvidersTab v-else-if="activeTab === 'models'" />
            <CodexProfilesSettingsTab v-else-if="activeTab === 'profiles'" />
            <SettingsSoundTab v-else-if="activeTab === 'sound'" />
            <component :is="activeFeatureSettingsComponent" v-else-if="activeFeatureSettingsComponent" />
            <SettingsUpdateTab v-else-if="activeTab === 'update'" />
            <EnvSetupDrawer v-else-if="activeTab === 'env'" mode="settings" />
            <IntegrationsDrawer v-else-if="activeTab === 'integrations'" mode="settings" />
            <GlobalConfigDrawer v-else mode="settings" />
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, watch } from "vue";
import { useI18n } from "vue-i18n";
import { Bell, Bot, Cpu, Download, Image, PlugZap, Settings2, SlidersHorizontal, Workflow } from "lucide-vue-next";
import { useAppShellStore } from "../../stores/appShell.store";
import { FEATURE_SETTINGS_TABS, getFeatureSettingsByTab } from "../../features/registry";
import GlobalConfigDrawer from "./overlays/GlobalConfigDrawer.vue";
import EnvSetupDrawer from "./overlays/EnvSetupDrawer.vue";
import IntegrationsDrawer from "./overlays/IntegrationsDrawer.vue";
import SettingsSoundTab from "./settings/SettingsSoundTab.vue";
import SettingsUpdateTab from "./settings/SettingsUpdateTab.vue";
import CodexProfilesSettingsTab from "./settings/CodexProfilesSettingsTab.vue";
import SettingsModelProvidersTab from "./settings/SettingsModelProvidersTab.vue";

const appShellStore = useAppShellStore();
const { t } = useI18n();
const activeTab = computed(() => appShellStore.settingsActiveTab);
const settingsFeatureIconByName = {
  image: Image,
  workflow: Workflow,
} as const;
const activeFeatureSettingsComponent = computed(() => getFeatureSettingsByTab(activeTab.value)?.component ?? null);
const tabGroups = computed(() => [
  {
    label: t("settings.groups.basics"),
    items: [
      {
        key: "global" as const,
        label: t("settings.tabs.global"),
        desc: t("settings.tabs.globalDesc"),
        icon: SlidersHorizontal,
      },
      {
        key: "models" as const,
        label: t("settings.tabs.models"),
        desc: t("settings.tabs.modelsDesc"),
        icon: Cpu,
      },
      {
        key: "profiles" as const,
        label: t("settings.tabs.profiles"),
        desc: t("settings.tabs.profilesDesc"),
        icon: Bot,
      },
    ],
  },
  {
    label: t("settings.groups.extensions"),
    items: [
      {
        key: "integrations" as const,
        label: t("settings.tabs.integrations"),
        desc: t("settings.tabs.integrationsDesc"),
        icon: PlugZap,
      },
      ...FEATURE_SETTINGS_TABS.map((tab) => ({
        key: tab.tab,
        label: t(tab.labelKey),
        desc: t(tab.descKey),
        icon: settingsFeatureIconByName[tab.icon],
      })),
    ],
  },
  {
    label: t("settings.groups.runtime"),
    items: [
      {
        key: "sound" as const,
        label: t("settings.tabs.sound"),
        desc: t("settings.tabs.soundDesc"),
        icon: Bell,
      },
      {
        key: "update" as const,
        label: t("settings.tabs.update"),
        desc: t("settings.tabs.updateDesc"),
        icon: Download,
      },
      {
        key: "env" as const,
        label: t("settings.tabs.env"),
        desc: t("settings.tabs.envDesc"),
        icon: Settings2,
      },
    ],
  },
]);

watch(
  () => appShellStore.settingsOpen,
  (open) => {
    if (!open) return;
    // Settings 页进入时保持 Integrations 子 tab 同步到 store，确保从 MCP 跳转能落地。
    if (activeTab.value === "integrations") {
      appShellStore.setSettingsIntegrationsTab(appShellStore.settingsIntegrationsTab);
    }
  }
);
</script>

// packages/app/src/renderer/components/layout/SettingsPage.tsx
import { Bell, Bot, Download, Image, PlugZap, Settings2, SlidersHorizontal, Workflow } from "lucide-react";
import { useEffect } from "react";
import { useAppShellStore, type SettingsTab } from "../../stores/appShell.store";
import { FEATURE_SETTINGS_TABS, getFeatureSettingsByTab } from "../../features/registry";
import { translate } from "../../i18n/translate";
import GlobalConfigDrawer from "./overlays/GlobalConfigDrawer";
import EnvSetupDrawer from "./overlays/EnvSetupDrawer";
import IntegrationsDrawer from "./overlays/IntegrationsDrawer";
import CodexProfilesSettingsTab from "./settings/CodexProfilesSettingsTab";
import SettingsSoundTab from "./settings/SettingsSoundTab";
import SettingsUpdateTab from "./settings/SettingsUpdateTab";

export default function SettingsPage() {
  const appShellStore = useAppShellStore();
  const activeTab = appShellStore.settingsActiveTab;
  const featureSettings = getFeatureSettingsByTab(activeTab);
  const FeatureSettingsComponent = featureSettings?.component ?? null;
  const featureIconByName = { image: Image, workflow: Workflow } as const;
  const tabGroups = [
    {
      label: translate("settings.groups.basics"),
      items: [
        { key: "global" as const, label: translate("settings.tabs.global"), desc: translate("settings.tabs.globalDesc"), icon: SlidersHorizontal },
        { key: "profiles" as const, label: translate("settings.tabs.profiles"), desc: translate("settings.tabs.profilesDesc"), icon: Bot },
      ],
    },
    {
      label: translate("settings.groups.extensions"),
      items: [
        { key: "integrations" as const, label: translate("settings.tabs.integrations"), desc: translate("settings.tabs.integrationsDesc"), icon: PlugZap },
        ...FEATURE_SETTINGS_TABS.map((tab) => ({
          key: tab.tab,
          label: translate(tab.labelKey),
          desc: translate(tab.descKey),
          icon: featureIconByName[tab.icon],
        })),
      ],
    },
    {
      label: translate("settings.groups.runtime"),
      items: [
        { key: "sound" as const, label: translate("settings.tabs.sound"), desc: translate("settings.tabs.soundDesc"), icon: Bell },
        { key: "update" as const, label: translate("settings.tabs.update"), desc: translate("settings.tabs.updateDesc"), icon: Download },
        { key: "env" as const, label: translate("settings.tabs.env"), desc: translate("settings.tabs.envDesc"), icon: Settings2 },
      ],
    },
  ];

  useEffect(() => {
    if (appShellStore.settingsOpen && activeTab === "integrations") {
      appShellStore.setSettingsIntegrationsTab(appShellStore.settingsIntegrationsTab);
    }
  }, [appShellStore.settingsOpen, activeTab]);

  return (
    <section className="settings-page" aria-label={translate("settings.pageAria")}>
      <div className="settings-workspace">
      <aside className="settings-sidebar app-scrollbar" aria-label={translate("settings.sidebarAria")}>
        <nav className="settings-nav" role="tablist" aria-label={translate("settings.tabsAria")}>
          {tabGroups.map((group) => (
            <section key={group.label} className="settings-nav-group">
              <div className="settings-nav-section">{group.label}</div>
              {group.items.map((tab) => {
                const Icon = tab.icon;
                const active = activeTab === tab.key;
                return (
                  <button
                    key={tab.key}
                    className={`settings-nav-item${active ? " is-active" : ""}`}
                    type="button"
                    role="tab"
                    aria-selected={active}
                    onClick={() => appShellStore.setSettingsTab(tab.key as SettingsTab)}
                  >
                    <Icon className="settings-nav-icon" aria-hidden="true" />
                    <span className="settings-nav-copy">
                      <span className="settings-nav-label">{tab.label}</span>
                      <span className="settings-nav-desc">{tab.desc}</span>
                    </span>
                  </button>
                );
              })}
            </section>
          ))}
        </nav>
      </aside>
      <div className="settings-scroll app-scrollbar">
        <div className="settings-stage">
          <div className="settings-tab-content" data-tab={activeTab}>
            {activeTab === "global" ? <GlobalConfigDrawer mode="settings" /> : null}
            {activeTab === "profiles" ? <CodexProfilesSettingsTab /> : null}
            {activeTab === "sound" ? <SettingsSoundTab /> : null}
            {FeatureSettingsComponent ? <FeatureSettingsComponent /> : null}
            {activeTab === "update" ? <SettingsUpdateTab /> : null}
            {activeTab === "env" ? <EnvSetupDrawer mode="settings" /> : null}
            {activeTab === "integrations" ? <IntegrationsDrawer mode="settings" /> : null}
            {!FeatureSettingsComponent &&
            activeTab !== "global" &&
            activeTab !== "profiles" &&
            activeTab !== "sound" &&
            activeTab !== "update" &&
            activeTab !== "env" &&
            activeTab !== "integrations" ? (
              <GlobalConfigDrawer mode="settings" />
            ) : null}
          </div>
        </div>
      </div>
      </div>
    </section>
  );
}
