// packages/app/src/renderer/App.tsx
import { type CSSProperties, type KeyboardEvent as ReactKeyboardEvent, useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import TopBar from "./components/layout/TopBar";
import CenterPane from "./components/layout/CenterPane";
import BottomBar from "./components/layout/BottomBar";
import RuntimeModeChooser from "./components/custom/RuntimeModeChooser";
import CustomWorkbench from "./components/custom/CustomWorkbench";
import AppClosingOverlay from "./components/layout/overlays/AppClosingOverlay";
import DebugTimelineSidebar from "./components/layout/debug/DebugTimelineSidebar";
import GoalShutdownCountdownOverlay from "./components/layout/overlays/GoalShutdownCountdownOverlay";
import LeftSidebar from "./components/layout/LeftSidebar";
import SettingsPage from "./components/layout/SettingsPage";
import WorkspaceEditorPane from "./components/layout/workspace/WorkspaceEditorPane";
import WorkspaceFilesSidebar from "./components/layout/workspace/WorkspaceFilesSidebar";
import {
  allowsWorkspaceFilesSidebar,
  getFeatureByMainView,
  shouldShowDefaultLeftSidebar,
} from "./features/registry";
import { codexDesktop } from "./api/codexDesktopClient";
import { useAppClosingStore } from "./stores/appClosing.store";
import { useAppShellStore } from "./stores/appShell.store";
import { useGoalShutdownStore } from "./stores/goalShutdown.store";
import { useNotificationSoundStore } from "./stores/notificationSound.store";
import { useRuntimeStore } from "./stores/runtime.store";
import { useModelCatalogStore } from "./stores/modelCatalog.store";
import { useWorkspaceFilesStore } from "./stores/workspaceFiles.store";
import type { AppWindowState } from "@codenexus/shared/ipc/contracts";
import {
  CENTER_BASE_MIN_WIDTH_PX,
  CENTER_EDITOR_HARD_MIN_WIDTH_PX,
  CENTER_EDITOR_SASH_WIDTH_PX,
  CENTER_EDITOR_SOFT_MIN_WIDTH_PX,
  CENTER_TIMELINE_HARD_MIN_WIDTH_PX,
  CENTER_WITH_EDITOR_HARD_MIN_WIDTH_PX,
  resolveCenterWidths,
  resolveShellWidths,
} from "./domain/layoutWidthBudget";

const UNIFIED_SIDEBAR_WIDTH_PX = 300;
const CENTER_EDITOR_KEYBOARD_STEP_PX = 20;

function isToggleDebugTimelineShortcut(event: KeyboardEvent) {
  if (event.isComposing) return false;
  if (!(event.ctrlKey || event.metaKey) || !event.altKey) return false;
  return event.code === "KeyJ";
}

function applyWindowStateToDocument(state: AppWindowState) {
  const windowMode = state.isFullScreen ? "fullscreen" : state.isMaximized ? "maximized" : "normal";
  try {
    document.documentElement.dataset.window = windowMode;
  } catch {}
}

export default function App() {
  const { t } = useTranslation();
  const appShellStore = useAppShellStore();
  const appClosingStore = useAppClosingStore();
  const goalShutdownStore = useGoalShutdownStore();
  const runtimeStore = useRuntimeStore();
  const notificationSoundStore = useNotificationSoundStore();
  const modelCatalogStore = useModelCatalogStore();
  const workspaceFilesStore = useWorkspaceFilesStore();
  const mainRef = useRef<HTMLElement | null>(null);
  const [editorResizeState, setEditorResizeState] = useState<{
    startClientX: number;
    startWidthPx: number;
    previewWidthPx: number;
  } | null>(null);

  useEffect(() => {
    appShellStore.initLocalSettings();
    runtimeStore.initLocalDraftState();
    notificationSoundStore.initLocalSettings();
    goalShutdownStore.initLocalSettings();
    modelCatalogStore.initLocalSettings();
    appClosingStore.initBridge();
    void notificationSoundStore.refreshAvailable();
  }, []);

  const settingsOpen = appShellStore.settingsOpen;
  const mainView = appShellStore.mainView;
  const isCustomMode = appShellStore.runtimeMode === "custom";
  const showModeChooser = appShellStore.runtimeMode === null || appShellStore.modeChooserOpen;
  const activeFeature = getFeatureByMainView(mainView);
  const featureWorkspaceSidebar =
    isCustomMode || settingsOpen || !appShellStore.leftSidebarVisible
      ? null
      : activeFeature?.workspaceSidebarComponent ?? null;
  const featureSettingsSidebar =
    isCustomMode || settingsOpen ? null : activeFeature?.settingsSidebarComponent ?? null;
  const showLeftSidebar =
    !isCustomMode &&
    !settingsOpen &&
    appShellStore.leftSidebarVisible &&
    !featureWorkspaceSidebar &&
    shouldShowDefaultLeftSidebar(mainView);
  const showLeftPane = Boolean(featureWorkspaceSidebar) || showLeftSidebar;
  const showDebugSidebar =
    !settingsOpen && runtimeStore.timelineDebugEnabled && (isCustomMode || mainView === "chat");
  const showFilesSidebar =
    !isCustomMode &&
    !settingsOpen &&
    allowsWorkspaceFilesSidebar(mainView) &&
    Boolean(String(runtimeStore.workspacePath ?? "").trim()) &&
    appShellStore.filesSidebarVisible &&
    !showDebugSidebar;
  const showEditorPane = !settingsOpen && mainView === "chat" && workspaceFilesStore.hasOpenTabs;
  const centerHardMinWidthPx = showEditorPane ? CENTER_WITH_EDITOR_HARD_MIN_WIDTH_PX : CENTER_BASE_MIN_WIDTH_PX;

  const getMainWidthPx = () => mainRef.current?.getBoundingClientRect().width ?? window.innerWidth;
  const resolvedShellWidths = useMemo(
    () =>
      resolveShellWidths({
        containerWidth: getMainWidthPx(),
        leftVisible: showLeftPane,
        filesVisible: showFilesSidebar || showDebugSidebar || Boolean(featureSettingsSidebar),
        rightVisible: false,
        leftPreferredWidth: UNIFIED_SIDEBAR_WIDTH_PX,
        filesPreferredWidth: UNIFIED_SIDEBAR_WIDTH_PX,
        rightPreferredWidth: 0,
        centerHardMinWidth: centerHardMinWidthPx,
        prioritySide: "left",
      }),
    [showLeftPane, showFilesSidebar, showDebugSidebar, featureSettingsSidebar, centerHardMinWidthPx]
  );
  const resolvedCenterWidths = useMemo(
    () =>
      resolveCenterWidths({
        containerWidth: resolvedShellWidths.centerWidth,
        editorVisible: showEditorPane,
        editorPreferredWidth: editorResizeState?.previewWidthPx ?? appShellStore.centerEditorWidthPx,
      }),
    [resolvedShellWidths.centerWidth, showEditorPane, editorResizeState?.previewWidthPx, appShellStore.centerEditorWidthPx]
  );
  const effectiveEditorWidthPx = resolvedCenterWidths.editorWidth;
  const isEditorCompact = showEditorPane && effectiveEditorWidthPx < CENTER_EDITOR_SOFT_MIN_WIDTH_PX;

  const setEditorResizeGlobalStyles = (enabled: boolean) => {
    try {
      document.body.style.cursor = enabled ? "col-resize" : "";
      document.body.style.userSelect = enabled ? "none" : "";
      document.body.classList.toggle("is-resizing", enabled);
    } catch {}
  };

  const clampEditorPreferredWidthPx = (value: number) => {
    const totalWidth = resolvedShellWidths.centerWidth;
    const maxWidth = Math.max(
      CENTER_EDITOR_HARD_MIN_WIDTH_PX,
      totalWidth - CENTER_EDITOR_SASH_WIDTH_PX - CENTER_TIMELINE_HARD_MIN_WIDTH_PX
    );
    return Math.max(CENTER_EDITOR_HARD_MIN_WIDTH_PX, Math.min(Math.round(value), maxWidth));
  };

  useEffect(() => {
    const onWindowKeydown = (event: KeyboardEvent) => {
      if (!isCustomMode || !isToggleDebugTimelineShortcut(event)) return;
      event.preventDefault();
      event.stopPropagation();
      runtimeStore.toggleTimelineDebugEnabled();
    };
    window.addEventListener("keydown", onWindowKeydown);

    void (async () => {
      try {
        applyWindowStateToDocument(await codexDesktop.window.getState());
      } catch {}
    })();

    let stopWindowStateListener: (() => void) | null = null;
    try {
      stopWindowStateListener = codexDesktop.window.onState((payload) => {
        applyWindowStateToDocument(payload);
      });
    } catch {}

    return () => {
      window.removeEventListener("keydown", onWindowKeydown);
      try {
        stopWindowStateListener?.();
      } catch {}
    };
  }, [isCustomMode, runtimeStore]);

  useEffect(() => {
    if (appClosingStore.phase !== "preparing") return;
    void runtimeStore.flushPendingComposeStateSaves().catch((error: unknown) => {
      console.warn("[App] flush pending compose state saves failed", error);
    });
  }, [appClosingStore.phase, runtimeStore]);

  useEffect(() => {
    if (showEditorPane) return;
    setEditorResizeState(null);
    setEditorResizeGlobalStyles(false);
  }, [showEditorPane]);

  useEffect(() => {
    if (!editorResizeState) return;
    const onPointerMove = (event: PointerEvent) => {
      setEditorResizeState((state) => {
        if (!state) return state;
        const deltaX = state.startClientX - event.clientX;
        return { ...state, previewWidthPx: clampEditorPreferredWidthPx(state.startWidthPx + deltaX) };
      });
    };
    const onPointerUp = () => {
      setEditorResizeState((state) => {
        if (state) {
          appShellStore.setCenterEditorWidthPx(clampEditorPreferredWidthPx(state.previewWidthPx), { save: true });
        }
        return null;
      });
      setEditorResizeGlobalStyles(false);
    };
    window.addEventListener("pointermove", onPointerMove);
    window.addEventListener("pointerup", onPointerUp);
    window.addEventListener("pointercancel", onPointerUp);
    return () => {
      window.removeEventListener("pointermove", onPointerMove);
      window.removeEventListener("pointerup", onPointerUp);
      window.removeEventListener("pointercancel", onPointerUp);
      setEditorResizeGlobalStyles(false);
    };
  }, [editorResizeState, appShellStore, resolvedShellWidths.centerWidth]);

  const onEditorSashPointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    if (!showEditorPane || event.button !== 0) return;
    setEditorResizeState({
      startClientX: event.clientX,
      startWidthPx: effectiveEditorWidthPx,
      previewWidthPx: effectiveEditorWidthPx,
    });
    setEditorResizeGlobalStyles(true);
    try {
      event.currentTarget.setPointerCapture(event.pointerId);
    } catch {}
    event.preventDefault();
  };

  const onEditorSashKeydown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    if (!showEditorPane) return;
    if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
    const delta = event.key === "ArrowLeft" ? CENTER_EDITOR_KEYBOARD_STEP_PX : -CENTER_EDITOR_KEYBOARD_STEP_PX;
    appShellStore.setCenterEditorWidthPx(clampEditorPreferredWidthPx(effectiveEditorWidthPx + delta), {
      save: true,
    });
    event.preventDefault();
  };

  const FeatureWorkspaceSidebar = featureWorkspaceSidebar;
  const FeatureWorkbench = activeFeature?.workbenchComponent ?? null;
  const FeatureSettingsSidebar = featureSettingsSidebar;

  const mainClass = [
    "main",
    !settingsOpen && showEditorPane ? "has-editor" : "",
    showFilesSidebar || showDebugSidebar || Boolean(featureSettingsSidebar) ? "has-files-sidebar" : "",
    mainView === "image" && featureSettingsSidebar ? "has-image-sidebar" : "",
    mainView === "paper" && featureSettingsSidebar ? "has-paper-sidebar" : "",
    settingsOpen ? "has-settings" : "",
  ]
    .filter(Boolean)
    .join(" ");
  const mainStyle = {
    "--left-sidebar-w": `${Math.max(0, Math.round(resolvedShellWidths.leftWidth))}px`,
    "--files-sidebar-w": `${Math.max(0, Math.round(resolvedShellWidths.filesWidth))}px`,
    "--center-editor-w": `${Math.max(0, Math.round(effectiveEditorWidthPx))}px`,
    "--center-editor-sash-w": `${CENTER_EDITOR_SASH_WIDTH_PX}px`,
  } as CSSProperties;

  return (
    <div className="app-shell">
      <TopBar />
      <main ref={mainRef} className={mainClass} style={mainStyle}>
        {FeatureWorkspaceSidebar ? (
          <FeatureWorkspaceSidebar className="tasks-pane-host" />
        ) : showLeftSidebar ? (
          <LeftSidebar className="tasks-pane-host" />
        ) : null}

        <div className="center-content-host">
          {settingsOpen ? (
            <SettingsPage />
          ) : isCustomMode ? (
            <CustomWorkbench />
          ) : FeatureWorkbench ? (
            <FeatureWorkbench />
          ) : (
            <CenterPane />
          )}
        </div>

        {!settingsOpen && showEditorPane ? (
          <div
            className="center-workbench-sash"
            role="separator"
            aria-orientation="vertical"
            aria-label={t("appShell.resizeEditor")}
            aria-valuenow={Math.round(effectiveEditorWidthPx)}
            tabIndex={0}
            onPointerDown={onEditorSashPointerDown}
            onKeyDown={onEditorSashKeydown}
          />
        ) : null}
        {!settingsOpen && showEditorPane ? (
          <WorkspaceEditorPane className={`workspace-editor-pane-host${isEditorCompact ? " is-compact" : ""}`} />
        ) : null}

        {FeatureSettingsSidebar ? (
          <FeatureSettingsSidebar className="files-pane-host" />
        ) : showDebugSidebar ? (
          <DebugTimelineSidebar className="files-pane-host" />
        ) : showFilesSidebar ? (
          <WorkspaceFilesSidebar className="files-pane-host" />
        ) : null}
      </main>
      <BottomBar />
      <div className="app-overlays">
        {appClosingStore.visible ? <AppClosingOverlay /> : null}
        {goalShutdownStore.visible ? <GoalShutdownCountdownOverlay /> : null}
        {showModeChooser ? <RuntimeModeChooser /> : null}
      </div>
    </div>
  );
}

// packages/app/src/renderer/App.vue
<template>
  <div class="app-shell">
    <TopBar key="topbar" />
    <main ref="mainRef" class="main" :class="mainClass" :style="mainStyle">
      <Transition :name="leftPaneTransitionName" mode="out-in">
        <component
          :is="featureWorkspaceSidebar"
          v-if="featureWorkspaceSidebar"
          :key="`${mainView}-workspace`"
          class="tasks-pane-host"
        />
        <LeftSidebar v-else-if="showLeftSidebar" key="threads" class="tasks-pane-host" />
      </Transition>

      <Transition :name="mainViewTransitionName" mode="out-in">
        <div v-if="settingsOpen" key="settings" class="center-content-host">
          <SettingsPage />
        </div>
        <div v-else-if="isCustomMode" key="custom" class="center-content-host">
          <CustomWorkbench />
        </div>
        <div v-else-if="activeFeature" :key="activeFeature.mainView" class="center-content-host">
          <component :is="activeFeature.workbenchComponent" />
        </div>
        <div v-else key="chat" class="center-content-host">
          <CenterPane />
        </div>
      </Transition>
      <div
        v-if="!settingsOpen && showEditorPane"
        class="center-workbench-sash"
        role="separator"
        aria-orientation="vertical"
        :aria-label="t('appShell.resizeEditor')"
        :aria-valuenow="String(Math.round(effectiveEditorWidthPx))"
        tabindex="0"
        @pointerdown="onEditorSashPointerDown"
        @keydown="onEditorSashKeydown"
      ></div>
      <WorkspaceEditorPane
        v-if="!settingsOpen && showEditorPane"
        class="workspace-editor-pane-host"
        :class="{ 'is-compact': isEditorCompact }"
      />
      <Transition name="side-pane-switch" mode="out-in">
        <component
          :is="featureSettingsSidebar"
          v-if="featureSettingsSidebar"
          :key="`${mainView}-settings`"
          class="files-pane-host"
        />
        <DebugTimelineSidebar v-else-if="showDebugSidebar" key="debug" class="files-pane-host" />
        <WorkspaceFilesSidebar v-else-if="showFilesSidebar" key="files" class="files-pane-host" />
      </Transition>
    </main>
    <BottomBar />
    <div class="app-overlays">
      <AppClosingOverlay v-if="showAppClosingOverlay" />
      <GoalShutdownCountdownOverlay v-if="showGoalShutdownOverlay" />
      <RuntimeModeChooser v-if="showModeChooser" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import TopBar from "./components/layout/TopBar.vue";
import CenterPane from "./components/layout/CenterPane.vue";
import BottomBar from "./components/layout/BottomBar.vue";
import RuntimeModeChooser from "./components/custom/RuntimeModeChooser.vue";
import CustomWorkbench from "./components/custom/CustomWorkbench.vue";
import {
  AppClosingOverlay,
  DebugTimelineSidebar,
  GoalShutdownCountdownOverlay,
  LeftSidebar,
  SettingsPage,
  WorkspaceEditorPane,
  WorkspaceFilesSidebar,
} from "./components/asyncViews";
import {
  allowsWorkspaceFilesSidebar,
  getFeatureByMainView,
  mainViewTransitionOrder,
  shouldShowDefaultLeftSidebar,
} from "./features/registry";
import { codexDesktop } from "./api/codexDesktopClient";
import { useAppClosingStore } from "./stores/appClosing.store";
import { useAppShellStore } from "./stores/appShell.store";
import { useGoalShutdownStore } from "./stores/goalShutdown.store";
import { useNotificationSoundStore } from "./stores/notificationSound.store";
import { useRuntimeStore } from "./stores/runtime.store";
import { useModelCatalogStore } from "./stores/modelCatalog.store";
import { useWorkspaceFilesStore } from "./stores/workspaceFiles.store";
import type { AppWindowState } from "@codenexus/shared/ipc/contracts";
import {
  CENTER_BASE_MIN_WIDTH_PX,
  CENTER_EDITOR_HARD_MIN_WIDTH_PX,
  CENTER_EDITOR_SASH_WIDTH_PX,
  CENTER_EDITOR_SOFT_MIN_WIDTH_PX,
  CENTER_WITH_EDITOR_HARD_MIN_WIDTH_PX,
  CENTER_TIMELINE_HARD_MIN_WIDTH_PX,
  resolveCenterWidths,
  resolveShellWidths,
} from "./domain/layoutWidthBudget";

const appShellStore = useAppShellStore();
const { t } = useI18n();
const appClosingStore = useAppClosingStore();
const goalShutdownStore = useGoalShutdownStore();
const runtimeStore = useRuntimeStore();
const notificationSoundStore = useNotificationSoundStore();
const modelCatalogStore = useModelCatalogStore();
const workspaceFilesStore = useWorkspaceFilesStore();
appShellStore.initLocalSettings();
runtimeStore.initLocalDraftState();
notificationSoundStore.initLocalSettings();
goalShutdownStore.initLocalSettings();
modelCatalogStore.initLocalSettings();
appClosingStore.initBridge();
void notificationSoundStore.refreshAvailable();

const settingsOpen = computed(() => appShellStore.settingsOpen);
const showAppClosingOverlay = computed(() => appClosingStore.visible);
const showGoalShutdownOverlay = computed(() => goalShutdownStore.visible);
const mainView = computed(() => appShellStore.mainView);
const isCustomMode = computed(() => appShellStore.runtimeMode === "custom");
const showModeChooser = computed(() => appShellStore.runtimeMode === null || appShellStore.modeChooserOpen);
const activeFeature = computed(() => getFeatureByMainView(mainView.value));
const featureWorkspaceSidebar = computed(() => {
  if (isCustomMode.value || settingsOpen.value || !appShellStore.leftSidebarVisible) return null;
  return activeFeature.value?.workspaceSidebarComponent ?? null;
});
const featureSettingsSidebar = computed(() => {
  if (isCustomMode.value || settingsOpen.value) return null;
  return activeFeature.value?.settingsSidebarComponent ?? null;
});
const showLeftSidebar = computed(
  () =>
    !isCustomMode.value &&
    !settingsOpen.value &&
    appShellStore.leftSidebarVisible &&
    !featureWorkspaceSidebar.value &&
    shouldShowDefaultLeftSidebar(mainView.value)
);
const showLeftPane = computed(() => Boolean(featureWorkspaceSidebar.value) || showLeftSidebar.value);
const showDebugSidebar = computed(
  () =>
    !settingsOpen.value &&
    runtimeStore.timelineDebugEnabled &&
    (isCustomMode.value || mainView.value === "chat")
);
const showFilesSidebar = computed(() => {
  return (
    !isCustomMode.value &&
    !settingsOpen.value &&
    allowsWorkspaceFilesSidebar(mainView.value) &&
    Boolean(String(runtimeStore.workspacePath ?? "").trim()) &&
    appShellStore.filesSidebarVisible &&
    !showDebugSidebar.value
  );
});

let stopWindowStateListener: (() => void) | null = null;
const applyWindowStateToDocument = (state: AppWindowState) => {
  const windowMode = state.isFullScreen ? "fullscreen" : state.isMaximized ? "maximized" : "normal";
  try {
    document.documentElement.dataset.window = windowMode;
  } catch {}
};

onMounted(() => {
  window.addEventListener("keydown", onWindowKeydown);

  void (async () => {
    try {
      const state = await codexDesktop.window.getState();
      applyWindowStateToDocument(state);
    } catch {}
  })();

  try {
    stopWindowStateListener = codexDesktop.window.onState((payload) => {
      applyWindowStateToDocument(payload);
    });
  } catch {}
});

function onWindowKeydown(event: KeyboardEvent) {
  if (!isCustomMode.value || !isToggleDebugTimelineShortcut(event)) return;
  event.preventDefault();
  event.stopPropagation();
  runtimeStore.toggleTimelineDebugEnabled();
}

function isToggleDebugTimelineShortcut(event: KeyboardEvent) {
  if (event.isComposing) return false;
  if (!(event.ctrlKey || event.metaKey) || !event.altKey) return false;
  return event.code === "KeyJ";
}

watch(
  () => appClosingStore.phase,
  (phase, previousPhase) => {
    if (phase !== "preparing" || previousPhase === "preparing") return;
    void runtimeStore.flushPendingComposeStateSaves().catch((error) => {
      console.warn("[App] flush pending compose state saves failed", error);
    });
  }
);

const UNIFIED_SIDEBAR_WIDTH_PX = 300;
const CENTER_EDITOR_KEYBOARD_STEP_PX = 20;

const mainRef = ref<HTMLElement | null>(null);
const mainViewTransitionName = ref("main-view-fade");
const leftPaneTransitionName = ref("left-pane-switch-forward");
const editorResizeState = ref<{
  startClientX: number;
  startWidthPx: number;
  previewWidthPx: number;
} | null>(null);

watch(
  () => [appShellStore.mainView, appShellStore.settingsOpen] as const,
  ([nextView, nextSettingsOpen], [previousView, previousSettingsOpen]) => {
    if (nextSettingsOpen || previousSettingsOpen) {
      mainViewTransitionName.value = "main-view-fade";
      leftPaneTransitionName.value = "left-pane-switch-fade";
      return;
    }

    const nextOrder = mainViewTransitionOrder(nextView);
    const previousOrder = mainViewTransitionOrder(previousView);
    const isForward = nextOrder > previousOrder;
    const isBack = nextOrder < previousOrder;
    if (!isForward && !isBack) return;

    const direction = isForward ? "forward" : "back";
    mainViewTransitionName.value = `main-view-${direction}`;
    leftPaneTransitionName.value = `left-pane-switch-${direction}`;
  }
);

const showEditorPane = computed(
  () => !settingsOpen.value && mainView.value === "chat" && workspaceFilesStore.hasOpenTabs
);

const centerHardMinWidthPx = computed(() => {
  return showEditorPane.value ? CENTER_WITH_EDITOR_HARD_MIN_WIDTH_PX : CENTER_BASE_MIN_WIDTH_PX;
});

const resolvedShellWidths = computed(() => {
  return resolveShellWidths({
    containerWidth: getMainWidthPx(),
    leftVisible: showLeftPane.value,
    filesVisible: showFilesSidebar.value || showDebugSidebar.value || Boolean(featureSettingsSidebar.value),
    rightVisible: false,
    leftPreferredWidth: UNIFIED_SIDEBAR_WIDTH_PX,
    filesPreferredWidth: UNIFIED_SIDEBAR_WIDTH_PX,
    rightPreferredWidth: 0,
    centerHardMinWidth: centerHardMinWidthPx.value,
    prioritySide: "left",
  });
});

const effectiveLeftSidebarWidthPx = computed(() => {
  return resolvedShellWidths.value.leftWidth;
});

const effectiveFilesSidebarWidthPx = computed(() => {
  return resolvedShellWidths.value.filesWidth;
});

const resolvedCenterWidths = computed(() => {
  return resolveCenterWidths({
    containerWidth: resolvedShellWidths.value.centerWidth,
    editorVisible: showEditorPane.value,
    editorPreferredWidth: editorResizeState.value?.previewWidthPx ?? appShellStore.centerEditorWidthPx,
  });
});

const effectiveEditorWidthPx = computed(() => {
  return resolvedCenterWidths.value.editorWidth;
});

const isEditorCompact = computed(() => {
  return showEditorPane.value && effectiveEditorWidthPx.value < CENTER_EDITOR_SOFT_MIN_WIDTH_PX;
});

watch(
  showEditorPane,
  (visible) => {
    if (visible) return;
    editorResizeState.value = null;
    teardownEditorResizeListeners();
  },
  { flush: "post" }
);

const mainClass = computed(() => ({
  "has-editor": !settingsOpen.value && showEditorPane.value,
  "has-files-sidebar": showFilesSidebar.value || showDebugSidebar.value || Boolean(featureSettingsSidebar.value),
  "has-image-sidebar": mainView.value === "image" && Boolean(featureSettingsSidebar.value),
  "has-paper-sidebar": mainView.value === "paper" && Boolean(featureSettingsSidebar.value),
  "has-settings": settingsOpen.value,
}));

const mainStyle = computed(
  () =>
    ({
      "--left-sidebar-w": `${Math.max(0, Math.round(effectiveLeftSidebarWidthPx.value))}px`,
      "--files-sidebar-w": `${Math.max(0, Math.round(effectiveFilesSidebarWidthPx.value))}px`,
      "--center-editor-w": `${Math.max(0, Math.round(effectiveEditorWidthPx.value))}px`,
      "--center-editor-sash-w": `${CENTER_EDITOR_SASH_WIDTH_PX}px`,
    }) as Record<string, string>
);

const getMainWidthPx = () => mainRef.value?.getBoundingClientRect().width ?? window.innerWidth;

const clampEditorPreferredWidthPx = (value: number) => {
  const totalWidth = resolvedShellWidths.value.centerWidth;
  const maxWidth = Math.max(
    CENTER_EDITOR_HARD_MIN_WIDTH_PX,
    totalWidth - CENTER_EDITOR_SASH_WIDTH_PX - CENTER_TIMELINE_HARD_MIN_WIDTH_PX
  );
  return Math.max(CENTER_EDITOR_HARD_MIN_WIDTH_PX, Math.min(Math.round(value), maxWidth));
};

const setEditorResizeGlobalStyles = (enabled: boolean) => {
  try {
    document.body.style.cursor = enabled ? "col-resize" : "";
    document.body.style.userSelect = enabled ? "none" : "";
    document.body.classList.toggle("is-resizing", enabled);
  } catch {}
};

const teardownEditorResizeListeners = () => {
  window.removeEventListener("pointermove", onEditorSashPointerMove);
  window.removeEventListener("pointerup", onEditorSashPointerUp);
  window.removeEventListener("pointercancel", onEditorSashPointerUp);
  setEditorResizeGlobalStyles(false);
};

const onEditorSashPointerDown = (event: PointerEvent) => {
  if (!showEditorPane.value || event.button !== 0) return;
  editorResizeState.value = {
    startClientX: event.clientX,
    startWidthPx: effectiveEditorWidthPx.value,
    previewWidthPx: effectiveEditorWidthPx.value,
  };

  setEditorResizeGlobalStyles(true);
  try {
    (event.currentTarget as HTMLElement | null)?.setPointerCapture?.(event.pointerId);
  } catch {}

  window.addEventListener("pointermove", onEditorSashPointerMove);
  window.addEventListener("pointerup", onEditorSashPointerUp);
  window.addEventListener("pointercancel", onEditorSashPointerUp);
  event.preventDefault();
};

const onEditorSashPointerMove = (event: PointerEvent) => {
  const state = editorResizeState.value;
  if (!state) return;
  const deltaX = state.startClientX - event.clientX;
  state.previewWidthPx = clampEditorPreferredWidthPx(state.startWidthPx + deltaX);
};

const onEditorSashPointerUp = () => {
  const state = editorResizeState.value;
  editorResizeState.value = null;
  teardownEditorResizeListeners();
  if (!state) return;
  appShellStore.setCenterEditorWidthPx(clampEditorPreferredWidthPx(state.previewWidthPx), { save: true });
};

const onEditorSashKeydown = (event: KeyboardEvent) => {
  if (!showEditorPane.value) return;
  if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
  const delta = event.key === "ArrowLeft" ? CENTER_EDITOR_KEYBOARD_STEP_PX : -CENTER_EDITOR_KEYBOARD_STEP_PX;
  appShellStore.setCenterEditorWidthPx(clampEditorPreferredWidthPx(effectiveEditorWidthPx.value + delta), {
    save: true,
  });
  event.preventDefault();
};

onBeforeUnmount(() => {
  window.removeEventListener("keydown", onWindowKeydown);

  try {
    stopWindowStateListener?.();
  } catch {}
  stopWindowStateListener = null;

  teardownEditorResizeListeners();
});
</script>
