// packages/app/src/renderer/components/layout/skills/SkillsList.tsx
import { ChevronDown } from "lucide-react";
import type { SkillState } from "../../../domain/types";
import { translate } from "../../../i18n/translate";
import { useSkillsUiStore } from "../../../stores/skillsUi.store";

type SkillsListProps = {
  items?: SkillState[];
  mode?: "compact" | "manager";
  pendingPath?: string;
  stateText?: string;
  emptyText?: string;
  onToggleSkill?: (payload: { skill: SkillState; enabled: boolean }) => void;
  className?: string;
};

function skillKey(skill: SkillState) {
  return String(skill.path ?? "").trim() || String(skill.name ?? "").trim() || "unknown-skill";
}

function previewText(skill: SkillState) {
  const description = String(skill.description ?? "").trim();
  if (description) return description;
  if (!skill.configurable) return translate("skills.fixedPreview");
  return skill.enabled ? translate("skills.enabledPreview") : translate("skills.disabledPreview");
}

export default function SkillsList({
  items = [],
  mode = "compact",
  pendingPath = "",
  stateText = "",
  emptyText = translate("skills.empty"),
  onToggleSkill,
  className,
}: SkillsListProps) {
  const skillsUiStore = useSkillsUiStore();
  const modeClass = `skill-mode-${mode}`;

  if (stateText) return <div className={["skills-list", "skills-list--message", "dim", className].filter(Boolean).join(" ")}>{stateText}</div>;
  if (items.length === 0) return <div className={["skills-list", "skills-list--message", "dim", className].filter(Boolean).join(" ")}>{emptyText}</div>;

  return (
    <div className={["skills-list", modeClass, className].filter(Boolean).join(" ")}>
      {items.map((skill) => {
        const key = skillKey(skill);
        const open = skillsUiStore.isExpanded(key);
        const pending = pendingPath === String(skill.path ?? "");
        return (
          <article
            key={key}
            className={[
              "skill-details",
              modeClass,
              open ? "is-open" : "",
              !skill.configurable ? "is-readonly" : "",
              pending ? "is-pending" : "",
            ]
              .filter(Boolean)
              .join(" ")}
          >
            <div className={["skill-summary", modeClass].join(" ")}>
              <label className="skill-switch">
                <input
                  className="skill-switch-input"
                  type="checkbox"
                  checked={skill.enabled}
                  disabled={!skill.configurable || pending}
                  onClick={(event) => event.stopPropagation()}
                  onChange={(event) => onToggleSkill?.({ skill, enabled: event.currentTarget.checked })}
                />
                <span className="skill-switch-track" aria-hidden="true">
                  <span className="skill-switch-thumb" />
                </span>
              </label>

              <div className="skill-summary-main">
                <div className="skill-summary-topline">
                  <div className="skill-title-wrap">
                    <div className="name">{skill.name}</div>
                    {mode === "manager" ? (
                      <div className="skill-badge-row">
                        <span className={`skill-status-pill${skill.enabled ? " is-enabled" : " is-disabled"}`}>
                          {skill.enabled ? translate("skills.enabled") : translate("skills.disabled")}
                        </span>
                        <span className="skill-meta-pill">{skill.configurable ? translate("skills.configurable") : translate("skills.fixed")}</span>
                      </div>
                    ) : null}
                  </div>

                  {skill.description || skill.path ? (
                    <button
                      className="skill-summary-toggle"
                      type="button"
                      aria-label={open ? translate("skills.collapseDetails") : translate("skills.expandDetails")}
                      onClick={() => skillsUiStore.toggleExpanded(key)}
                    >
                      <ChevronDown className={`skill-summary-toggle-icon${open ? " open" : ""}`} aria-hidden="true" />
                    </button>
                  ) : null}
                </div>

                {mode === "manager" ? <div className="skill-preview">{previewText(skill)}</div> : null}
                {skill.path ? <div className="skill-path">{skill.path}</div> : null}
              </div>
            </div>

            {open ? (
              <div className={["skill-body", modeClass].join(" ")}>
                {skill.description ? (
                  <section className="skill-info-block">
                    <div className="skill-info-label mono">{translate("skills.description")}</div>
                    <div className="skill-desc">{skill.description}</div>
                  </section>
                ) : null}
                {skill.path ? (
                  <section className="skill-info-block">
                    <div className="skill-info-label mono">{translate("skills.path")}</div>
                    <div className="skill-path skill-path--body">{skill.path}</div>
                  </section>
                ) : null}
              </div>
            ) : null}
          </article>
        );
      })}
    </div>
  );
}

// packages/app/src/renderer/components/layout/skills/SkillsList.vue
<template>
  <div v-if="stateText" class="skills-list skills-list--message dim">{{ stateText }}</div>
  <div v-else-if="items.length === 0" class="skills-list skills-list--message dim">{{ emptyText }}</div>
  <div v-else class="skills-list" :class="modeClass">
    <article
      v-for="skill in items"
      :key="getSkillKey(skill)"
      class="skill-details"
      :class="[
        modeClass,
        { 'is-open': isSkillOpen(skill), 'is-readonly': !skill.configurable, 'is-pending': isSkillPending(skill) },
      ]"
    >
      <div class="skill-summary" :class="modeClass">
        <label class="skill-switch">
          <input
            class="skill-switch-input"
            type="checkbox"
            :checked="skill.enabled"
            :aria-label="skill.name"
            :disabled="!skill.configurable || isSkillPending(skill)"
            @click.stop
            @change="onSkillCheckboxChanged(skill, $event)"
          />
          <span class="skill-switch-track" aria-hidden="true">
            <span class="skill-switch-thumb"></span>
          </span>
        </label>

        <div class="skill-summary-main">
          <div class="skill-summary-topline">
            <div class="skill-title-wrap">
              <div class="name">{{ skill.name }}</div>
              <div v-if="mode === 'manager'" class="skill-badge-row">
                <span class="skill-status-pill" :class="skill.enabled ? 'is-enabled' : 'is-disabled'">
                  {{ skill.enabled ? t("skills.enabled") : t("skills.disabled") }}
                </span>
                <span class="skill-meta-pill">{{
                  skill.configurable ? t("skills.configurable") : t("skills.fixed")
                }}</span>
              </div>
            </div>

            <button
              v-if="skill.description || skill.path"
              class="skill-summary-toggle"
              type="button"
              :aria-label="isSkillOpen(skill) ? t('skills.collapseDetails') : t('skills.expandDetails')"
              @click="toggleSkillOpen(skill)"
            >
              <ChevronDown class="skill-summary-toggle-icon" :class="{ open: isSkillOpen(skill) }" aria-hidden="true" />
            </button>
          </div>

          <div v-if="mode === 'manager'" class="skill-preview">
            {{ previewText(skill) }}
          </div>

          <div v-if="skill.path" class="skill-path">{{ skill.path }}</div>
        </div>
      </div>

      <div v-if="isSkillOpen(skill)" class="skill-body" :class="modeClass">
        <section v-if="skill.description" class="skill-info-block">
          <div class="skill-info-label mono">{{ t("skills.description") }}</div>
          <div class="skill-desc">{{ skill.description }}</div>
        </section>

        <section v-if="skill.path" class="skill-info-block">
          <div class="skill-info-label mono">{{ t("skills.path") }}</div>
          <div class="skill-path skill-path--body">{{ skill.path }}</div>
        </section>
      </div>
    </article>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { ChevronDown } from "lucide-vue-next";
import type { SkillState } from "../../../domain/types";
import { useSkillsUiStore } from "../../../stores/skillsUi.store";

const props = withDefaults(
  defineProps<{
    items: SkillState[];
    mode?: "compact" | "manager";
    pendingPath?: string;
    stateText?: string;
    emptyText?: string;
  }>(),
  {
    mode: "compact",
    pendingPath: "",
    stateText: "",
    emptyText: "",
  }
);

const emit = defineEmits<{
  (event: "toggle-skill", payload: { skill: SkillState; enabled: boolean }): void;
}>();

const skillsUiStore = useSkillsUiStore();
const { t } = useI18n();
const modeClass = computed(() => `skill-mode-${props.mode}`);

const getSkillKey = (skill: SkillState): string => {
  const key = String(skill.path ?? "").trim() || String(skill.name ?? "").trim();
  return key || "unknown-skill";
};

const isSkillOpen = (skill: SkillState): boolean => skillsUiStore.isExpanded(getSkillKey(skill));
const toggleSkillOpen = (skill: SkillState): void => skillsUiStore.toggleExpanded(getSkillKey(skill));

const isSkillPending = (skill: SkillState): boolean => props.pendingPath === String(skill.path ?? "");

const previewText = (skill: SkillState): string => {
  const description = String(skill.description ?? "").trim();
  if (description) return description;
  if (!skill.configurable) return t("skills.fixedPreview");
  return skill.enabled ? t("skills.enabledPreview") : t("skills.disabledPreview");
};

const onSkillCheckboxChanged = (skill: SkillState, event: Event) => {
  const target = event.target as HTMLInputElement | null;
  emit("toggle-skill", { skill, enabled: Boolean(target?.checked) });
};
</script>
