// packages/app/src/renderer/components/chat/ChatAssistantMessage.tsx
import type { HTMLAttributes } from "react";
import type { MemoryCitation, MemoryCitationEntry } from "@codenexus/generated/codex-app-server/v2";
import type { TimelineEventItem } from "../../domain/types";
import {
  extractInlineMemoryCitation,
  stripInlineMemoryCitation,
  type ParsedMemoryCitation,
} from "../../domain/taggedMessageBlocks";
import { tryParseStructuredFinalAnswerV1 } from "../../domain/structuredFinalAnswer";
import { translate } from "../../i18n/translate";
import type { SandboxMode } from "../../stores/runtime.store";
import type { PlanDeltaExecUiState } from "../layout/types/chat.types";
import AgentMarkdownContent from "../ui/AgentMarkdownContent";
import MarkdownPlanOutputCard from "../ui/MarkdownPlanOutputCard";
import StructuredFinalAnswerCard from "../ui/StructuredFinalAnswerCard";
import ChatPlanDeltaActions from "./ChatPlanDeltaActions";

type Option = string | { value: string; label: string; disabled?: boolean };

export type ChatAssistantMessageProps = HTMLAttributes<HTMLDivElement> & {
  event?: TimelineEventItem;
  markdownHtml?: string;
  isStructuredFinalAnswer?: boolean;
  execState?: PlanDeltaExecUiState | null;
  modelOptions?: readonly Option[];
  isTurnRunning?: boolean;
  reasoningEffortOptions?: readonly Option[];
  sandboxModeOptions?: readonly Option[];
  onExecutePlan?: (event: TimelineEventItem) => void;
  onUpdateModel?: (value: string) => void;
  onUpdateReasoningEffort?: (value: string) => void;
  onUpdateSandboxMode?: (value: SandboxMode) => void;
};

function normalizeMemoryCitation(value: unknown): ParsedMemoryCitation | null {
  const citation = value && typeof value === "object" && !Array.isArray(value) ? (value as MemoryCitation) : null;
  if (!citation) return null;
  const entries = Array.isArray(citation.entries) ? citation.entries : [];
  const threadIds = Array.isArray(citation.threadIds) ? citation.threadIds : [];
  if (entries.length <= 0 && threadIds.length <= 0) return null;
  return { entries, threadIds, raw: "" };
}

function memoryCitationEntryLine(entry: MemoryCitationEntry) {
  const path = String(entry?.path ?? "").trim();
  const start = Number(entry?.lineStart ?? 0);
  const end = Number(entry?.lineEnd ?? 0);
  const range = start > 0 && end > 0 ? `${start}-${end}` : "";
  return range ? `${path}:${range}` : path;
}

export default function ChatAssistantMessage({
  event,
  markdownHtml,
  isStructuredFinalAnswer = false,
  execState = null,
  modelOptions = [],
  isTurnRunning = false,
  reasoningEffortOptions = [],
  sandboxModeOptions = [],
  onExecutePlan,
  onUpdateModel,
  onUpdateReasoningEffort,
  onUpdateSandboxMode,
  className,
  ...props
}: ChatAssistantMessageProps) {
  const rawText = String(event?.paramsText ?? "").trim();
  const displayText = stripInlineMemoryCitation(rawText);
  const isPlanDelta = event?.method === "item/plan/delta";
  const structured = isStructuredFinalAnswer || Boolean(tryParseStructuredFinalAnswerV1(displayText));
  const planActionDisabled = isTurnRunning || Boolean(execState?.executing);
  const shouldCollapsePlan = Boolean(execState?.collapseWhileExecuting && (execState.executing || isTurnRunning));
  const memoryCitation =
    normalizeMemoryCitation((event?.params as any)?.item?.memoryCitation) ?? extractInlineMemoryCitation(rawText);
  const memoryCitationEntries = memoryCitation?.entries ?? [];
  const memoryCitationThreadIds = memoryCitation?.threadIds ?? [];
  const memoryCitationRaw = memoryCitation?.raw ?? "";
  const memoryCitationSummary =
    memoryCitation && (memoryCitationEntries.length > 0 || memoryCitationThreadIds.length > 0 || memoryCitationRaw)
      ? translate("chat.memoryCitation.summary", {
          entries: memoryCitationEntries.length,
          threads: memoryCitationThreadIds.length,
        })
      : "";
  const planActions = execState && event ? (
    <ChatPlanDeltaActions
      execState={execState}
      modelOptions={modelOptions}
      reasoningEffortOptions={reasoningEffortOptions}
      sandboxModeOptions={sandboxModeOptions}
      disabled={planActionDisabled}
      embedded
      onExecutePlan={() => onExecutePlan?.(event)}
      onUpdateModel={onUpdateModel}
      onUpdateReasoningEffort={onUpdateReasoningEffort}
      onUpdateSandboxMode={onUpdateSandboxMode}
    />
  ) : null;
  const compactPlanActions = execState && event ? (
    <ChatPlanDeltaActions
      execState={execState}
      modelOptions={modelOptions}
      reasoningEffortOptions={reasoningEffortOptions}
      sandboxModeOptions={sandboxModeOptions}
      disabled={planActionDisabled}
      embedded
      compact
      onExecutePlan={() => onExecutePlan?.(event)}
      onUpdateModel={onUpdateModel}
      onUpdateReasoningEffort={onUpdateReasoningEffort}
      onUpdateSandboxMode={onUpdateSandboxMode}
    />
  ) : null;

  return (
    <div {...props} className={["chat-row flex min-w-0 m-0 chat-row--assistant", className].filter(Boolean).join(" ")}>
      <div className="chat-bubble chat-bubble-assistant w-full max-w-full min-w-0 px-1 py-2 text-sm">
        {isPlanDelta ? (
          <MarkdownPlanOutputCard
            rawText={rawText}
            forceCollapsed={shouldCollapsePlan}
            headerActions={compactPlanActions}
            actions={planActions}
          />
        ) : structured ? (
          <StructuredFinalAnswerCard className="chat-bubble-body min-w-0" rawText={displayText} />
        ) : (
          <AgentMarkdownContent
            className="chat-bubble-body agent-markdown-body min-w-0"
            html={displayText === rawText ? markdownHtml || undefined : undefined}
            markdown={displayText === rawText && markdownHtml ? undefined : displayText}
          />
        )}
        {memoryCitationSummary ? (
          <details className="assistant-memory-citation">
            <summary className="assistant-memory-citation__summary mono">{memoryCitationSummary}</summary>
            <div className="assistant-memory-citation__body">
              {memoryCitationEntries.length > 0 ? (
                <ul className="assistant-memory-citation__entries">
                  {memoryCitationEntries.map((entry) => (
                    <li key={`${entry.path}:${entry.lineStart}:${entry.lineEnd}`}>
                      <div className="assistant-memory-citation__path mono">{memoryCitationEntryLine(entry)}</div>
                      {entry.note ? <div className="assistant-memory-citation__note">{entry.note}</div> : null}
                    </li>
                  ))}
                </ul>
              ) : null}
              {memoryCitationThreadIds.length > 0 ? (
                <div className="assistant-memory-citation__threads mono">
                  {translate("chat.memoryCitation.threadIds")} {memoryCitationThreadIds.join(", ")}
                </div>
              ) : null}
              {memoryCitationEntries.length === 0 && memoryCitationThreadIds.length === 0 && memoryCitationRaw ? (
                <pre className="assistant-memory-citation__raw mono">{memoryCitationRaw}</pre>
              ) : null}
            </div>
          </details>
        ) : null}
      </div>
    </div>
  );
}

// packages/app/src/renderer/components/chat/ChatAssistantMessage.vue
<template>
  <div :class="[CHAT_ROW_BASE_CLASS, 'chat-row--assistant']">
    <div class="chat-bubble chat-bubble-assistant w-full max-w-full min-w-0">
      <section v-if="toolPause" class="tool-pause-card" role="status" aria-live="polite">
        <StatusIndicator state="warning" :label="zh ? '任务已暂停' : 'Task paused'" />
        <p>
          {{
            zh
              ? "工具调用达到安全保护条件。最新工具结果已保留。"
              : "Tool calls reached a safety condition. The latest results are preserved."
          }}
        </p>
        <button
          type="button"
          class="tool-pause-continue"
          :disabled="isTurnRunning || continuing || continued"
          @click="continueAnalysis"
        >
          {{
            continuing
              ? zh
                ? "正在继续…"
                : "Continuing…"
              : continued
                ? zh
                  ? "已继续"
                  : "Continued"
                : zh
                  ? "继续分析"
                  : "Continue analysis"
          }}
        </button>
        <p v-if="continueFailed" role="alert">
          {{ zh ? "暂未能继续，请重试或查看任务状态。" : "Unable to continue. Retry or check the task status." }}
        </p>
        <details>
          <summary>{{ zh ? "技术详情" : "Technical details" }}</summary>
          <p>{{ toolPause.reason }} · {{ toolPause.detail }} · {{ toolPause.rounds }} / {{ toolPause.limit }}</p>
        </details>
      </section>
      <MarkdownPlanOutputCard v-else-if="isPlanDelta" :rawText="event.paramsText" :forceCollapsed="shouldCollapsePlan">
        <template v-if="execState" #headerActions>
          <ChatPlanDeltaActions
            :execState="execState"
            :modelOptions="modelOptions"
            :reasoningEffortOptions="reasoningEffortOptions"
            :sandboxModeOptions="sandboxModeOptions"
            :disabled="planActionDisabled"
            embedded
            compact
            @execute-plan="$emit('execute-plan', event)"
            @update:model="(value) => $emit('update:model', value)"
            @update:reasoning-effort="(value) => $emit('update:reasoning-effort', value)"
            @update:sandbox-mode="(value) => $emit('update:sandbox-mode', value)"
          />
        </template>
        <template v-if="execState" #actions>
          <ChatPlanDeltaActions
            :execState="execState"
            :modelOptions="modelOptions"
            :reasoningEffortOptions="reasoningEffortOptions"
            :sandboxModeOptions="sandboxModeOptions"
            :disabled="planActionDisabled"
            :embedded="true"
            @execute-plan="$emit('execute-plan', event)"
            @update:model="(value) => $emit('update:model', value)"
            @update:reasoning-effort="(value) => $emit('update:reasoning-effort', value)"
            @update:sandbox-mode="(value) => $emit('update:sandbox-mode', value)"
          />
        </template>
      </MarkdownPlanOutputCard>
      <StructuredFinalAnswerCard
        v-else-if="isStructuredFinalAnswer"
        class="chat-bubble-body min-w-0"
        :rawText="assistantDisplayText"
      />
      <AgentMarkdownContent v-else class="chat-bubble-body agent-markdown-body min-w-0" :html="markdownHtml" />
      <details v-if="memoryCitationSummary" class="assistant-memory-citation">
        <summary class="assistant-memory-citation__summary mono">{{ memoryCitationSummary }}</summary>
        <div class="assistant-memory-citation__body">
          <ul v-if="memoryCitationEntries.length > 0" class="assistant-memory-citation__entries">
            <li v-for="entry in memoryCitationEntries" :key="`${entry.path}:${entry.lineStart}:${entry.lineEnd}`">
              <div class="assistant-memory-citation__path mono">{{ memoryCitationEntryLine(entry) }}</div>
              <div v-if="entry.note" class="assistant-memory-citation__note">{{ entry.note }}</div>
            </li>
          </ul>
          <div v-if="memoryCitationThreadIds.length > 0" class="assistant-memory-citation__threads mono">
            {{ t("chat.memoryCitation.threadIds") }} {{ memoryCitationThreadIds.join(", ") }}
          </div>
          <pre
            v-if="memoryCitationEntries.length === 0 && memoryCitationThreadIds.length === 0 && memoryCitationRaw"
            class="assistant-memory-citation__raw mono"
            >{{ memoryCitationRaw }}</pre
          >
        </div>
      </details>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, defineAsyncComponent, defineComponent, h, ref } from "vue";
import { parseToolPause } from "../../domain/toolPause";
import { getRuntimeOrchestrator } from "../../domain/runtimeOrchestrator";
import StatusIndicator from "../ui/StatusIndicator.vue";
import { useI18n } from "vue-i18n";
import AgentMarkdownContent from "../ui/AgentMarkdownContent.vue";
import ChatPlanDeltaActions from "./ChatPlanDeltaActions.vue";
import type { TimelineEventItem } from "../../domain/types";
import type { PlanDeltaExecUiState } from "../layout/types/chat.types";
import type { SandboxMode } from "../../stores/runtime.store";
import { CHAT_ROW_BASE_CLASS } from "../layout/chat/chatPresentation";
import {
  extractInlineMemoryCitation,
  stripInlineMemoryCitation,
  type ParsedMemoryCitation,
} from "../../domain/taggedMessageBlocks";
import type { MemoryCitation, MemoryCitationEntry } from "@codenexus/generated/codex-app-server/v2";

type OptionInput =
  | string
  | {
      value: string;
      label: string;
      disabled?: boolean;
    };

const AssistantCardLoading = defineComponent({
  name: "AssistantCardLoading",
  setup() {
    return () =>
      h("div", { class: "assistant-card-loading", "aria-hidden": "true" }, [
        h("div", { class: "assistant-card-loading__line assistant-card-loading__line--wide" }),
        h("div", { class: "assistant-card-loading__line assistant-card-loading__line--short" }),
      ]);
  },
});

const MarkdownPlanOutputCard = defineAsyncComponent({
  loader: () => import("../ui/MarkdownPlanOutputCard.vue"),
  loadingComponent: AssistantCardLoading,
  delay: 120,
});
const StructuredFinalAnswerCard = defineAsyncComponent({
  loader: () => import("../ui/StructuredFinalAnswerCard.vue"),
  loadingComponent: AssistantCardLoading,
  delay: 120,
});

const props = defineProps<{
  event: TimelineEventItem;
  isStructuredFinalAnswer: boolean;
  markdownHtml: string;
  execState: PlanDeltaExecUiState | null;
  modelOptions: readonly OptionInput[];
  isTurnRunning: boolean;
  reasoningEffortOptions: readonly OptionInput[];
  sandboxModeOptions: readonly OptionInput[];
}>();

const { t, locale } = useI18n();
const zh = computed(() => locale.value.startsWith("zh"));
const toolPause = computed(() => parseToolPause(props.event.paramsText));
const continuing = ref(false);
const continued = ref(false);
const continueFailed = ref(false);
async function continueAnalysis() {
  if (continuing.value || continued.value || props.isTurnRunning) return;
  continuing.value = true;
  continueFailed.value = false;
  try {
    continued.value = await getRuntimeOrchestrator().continueToolPausedTurn(props.event.threadId, props.event.id);
    continueFailed.value = !continued.value;
  } catch {
    continueFailed.value = true;
  } finally {
    continuing.value = false;
  }
}
const isPlanDelta = computed(() => props.event.method === "item/plan/delta");
const assistantDisplayText = computed(() => stripInlineMemoryCitation(props.event.paramsText));
const planActionDisabled = computed(() => props.isTurnRunning || Boolean(props.execState?.executing));
const shouldCollapsePlan = computed(() => {
  const state = props.execState;
  if (!state?.collapseWhileExecuting) return false;
  return Boolean(state.executing || props.isTurnRunning);
});
const normalizeMemoryCitation = (value: unknown): ParsedMemoryCitation | null => {
  const citation = value && typeof value === "object" && !Array.isArray(value) ? (value as MemoryCitation) : null;
  if (!citation) return null;
  const entries = Array.isArray(citation.entries) ? citation.entries : [];
  const threadIds = Array.isArray(citation.threadIds) ? citation.threadIds : [];
  if (entries.length <= 0 && threadIds.length <= 0) return null;
  return { entries, threadIds, raw: "" };
};

const memoryCitation = computed<ParsedMemoryCitation | null>(() => {
  const params = props.event.params as any;
  const citation = params?.item?.memoryCitation;
  return normalizeMemoryCitation(citation) ?? extractInlineMemoryCitation(props.event.paramsText);
});
const memoryCitationSummary = computed(() => {
  const citation = memoryCitation.value;
  if (!citation) return "";
  const entries = Array.isArray(citation.entries) ? citation.entries.length : 0;
  const threads = Array.isArray(citation.threadIds) ? citation.threadIds.length : 0;
  if (entries <= 0 && threads <= 0 && !citation.raw) return "";
  return t("chat.memoryCitation.summary", { entries, threads });
});
const memoryCitationEntries = computed(() => memoryCitation.value?.entries ?? []);
const memoryCitationThreadIds = computed(() => memoryCitation.value?.threadIds ?? []);
const memoryCitationRaw = computed(() => memoryCitation.value?.raw ?? "");
const memoryCitationEntryLine = (entry: MemoryCitationEntry) => {
  const path = String(entry?.path ?? "").trim();
  const start = Number(entry?.lineStart ?? 0);
  const end = Number(entry?.lineEnd ?? 0);
  const range = start > 0 && end > 0 ? `${start}-${end}` : "";
  return range ? `${path}:${range}` : path;
};

defineEmits<{
  (e: "execute-plan", event: TimelineEventItem): void;
  (e: "update:model", value: string): void;
  (e: "update:reasoning-effort", value: string): void;
  (e: "update:sandbox-mode", value: SandboxMode): void;
}>();
</script>

<style scoped>
.assistant-card-loading {
  display: grid;
  min-height: 64px;
  gap: 8px;
  border: 1px solid color-mix(in srgb, var(--ui-well-border) 76%, transparent);
  border-radius: 12px;
  background: color-mix(in srgb, var(--ui-well-bg) 82%, transparent);
  padding: 12px;
}

.assistant-card-loading__line {
  height: 8px;
  border-radius: 999px;
  background: color-mix(in srgb, var(--text-muted) 18%, transparent);
}

.assistant-card-loading__line--wide {
  width: min(300px, 76%);
}

.assistant-card-loading__line--short {
  width: min(190px, 48%);
}

.assistant-memory-citation {
  margin-top: 8px;
  border-top: 1px solid color-mix(in srgb, var(--border) 60%, transparent);
  padding-top: 6px;
  color: var(--text-muted);
  font-size: 11px;
}

.assistant-memory-citation__summary {
  cursor: pointer;
  user-select: none;
}

.assistant-memory-citation__body {
  margin-top: 6px;
  max-height: 180px;
  overflow: auto;
  border-radius: 4px;
  background: var(--ui-code-bg);
  padding: 8px;
  color: var(--ui-code-text);
}

.assistant-memory-citation__entries {
  display: grid;
  gap: 7px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.assistant-memory-citation__path {
  overflow-wrap: anywhere;
  color: var(--ui-code-text);
  font-size: 11px;
}

.assistant-memory-citation__note {
  margin-top: 2px;
  overflow-wrap: anywhere;
  color: var(--text-muted);
  font-size: 11px;
  line-height: 1.45;
}

.assistant-memory-citation__threads {
  margin-top: 8px;
  overflow-wrap: anywhere;
  color: var(--text-muted);
  font-size: 11px;
}

.assistant-memory-citation__raw {
  margin: 0;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  color: var(--ui-code-text);
  font-size: 11px;
}
</style>

<style scoped>
.tool-pause-card {
  display: grid;
  gap: 12px;
  padding: 16px;
  border: 1px solid var(--border);
  border-radius: 12px;
}
.tool-pause-card p {
  margin: 0;
}
.tool-pause-continue {
  justify-self: start;
  padding: 8px 16px;
  border: 1px solid var(--border);
  border-radius: 8px;
}
.tool-pause-continue:disabled {
  opacity: 0.5;
  cursor: default;
}
.tool-pause-card details {
  color: var(--text-muted);
  font-size: 12px;
}
</style>
